// ==================== CATÁLOGO DE CÓDIGOS INSTITUCIONALES (1000 registros) ====================
const CODIGOS_PERSONAL = {
  '3397': 'FLORES TORRES RAUL ANTONIO',
  '3406': 'POZO MOREIRA GERARDO LEONEL',
  '3508': 'TAPIA LOPEZ CARLOS ALBERTO',
  '3601': 'BALLADARES LARRAGA MANUEL',
  '3630': 'VACA DIAZ  MARIA JUDITH',
  '3664': 'GORDILLO QUITO ALBINO',
  '3666': 'HERRERA GUSTAY  MESIAS',
  '3674': 'NARANJO MARTINEZ LUCIANO EVARISTO',
  '3717': 'GALARZA HUERTAS MAGNO RAFAEL',
  '3735': 'ALCIVAR BAJAÑA PATRICIO',
  '3767': 'HERAS BUENO MANUEL RAUL',
  '3823': 'RUIZ BENAVIDEZ HUGO LEONCIO',
  '3837': 'AVILES PACHECO GALO LEONARDO',
  '3854': 'CASTRO SALAVARRIA ANDRES',
  '3856': 'BOADA AGUIÑO ENRIQUE',
  '3862': 'SANCHEZ VELASQUEZ FELIX OSWALDO',
  '3871': 'ERAZO HIDALGO SILVERIO',
  '3878': 'UBILLA BAJAÑA WILLIAMS',
  '3879': 'RAMIREZ HERRERA CARLOS',
  '3880': 'DENEGRI GUAGUA NERY ROBERTO',
  '3883': 'HIDALGO SILVA JOSE JOVITO',
  '3887': 'MONTALVAN RENDON CESAR RICARDO',
  '3901': 'NIEVES LOPEZ FELIPE JOHN',
  '3902': 'LEON RUIZ NESTOR JHONSON',
  '3903': 'MONGE MAGI JORGE ANTONIO',
  '3910': 'ALVARADO LARENAS MILTON',
  '3924': 'PEREZ DUARTE CARLOS ANTONIO',
  '3926': 'VILLALVA SALAZAR JORGE ABRAHAN',
  '3927': 'SANTOS GUILLEN LEDWIN',
  '3942': 'PALMA BAJAÑA JIMMY ADALBERTO',
  '3945': 'MORAN CHACON YORYI PATRICIO',
  '3946': 'VILLALTA GONZALEZ WALTER',
  '3953': 'SANCHEZ SANCHEZ ALEX ASTOLFO',
  '3954': 'VELASCO GARCIA FRANCISCO CARLOS',
  '3960': 'VELASCO VELASCO EDISON GERMAN',
  '3962': 'VALAREZO MALDONADO GONZALO',
  '3963': 'CARBONELL CEDEÑO FREDDY',
  '3965': 'CALDERON SALAVARRIA FAUSTINO',
  '3966': 'ARIAS MARURI IVAN FERNANDO',
  '3967': 'JARAMILLO PROAÑO CARLOS IVAN',
  '3985': 'SOTO ALDAZ ABELARDO',
  '3990': 'TELLO ABREO EDGAR ALFONSO',
  '3992': 'OYERVIDE HERMIDA RENE MARCELO',
  '3995': 'MEJIA SANCHEZ ROBERTO SABINO',
  '3996': 'MARTINEZ NAVARRETE NERU RAFAEL',
  '3997': 'TRIVIÑO BERMELLO JORGE FELIPE',
  '3998': 'HERNANDEZ ALVAREZ CARLOS',
  '4001': 'PALACIOS VERGARA JAIME',
  '4005': 'PINCAY AGUILERA JOSE OTTON',
  '4007': 'ALDAS ACOSTA JOSE OSWALDO',
  '4016': 'BERMUDES CHUMAÑA FREDDY',
  '4027': 'RONQUILLO MUÑOZ JHONNY JOSE',
  '4030': 'GARCIA JIMENEZ JOHN ENRIQUE',
  '4034': 'CHACON COELLO MIGUEL JOSE',
  '4035': 'CHONILLO YAGUAL ENRIQUE ALBERTO',
  '4037': 'DIAZ PLAZA FREDDY MANUEL',
  '4039': 'SERNA ALAVA JULIO CESAR',
  '4042': 'TORRES GARCIA CARLOS ROMAN',
  '4046': 'MORALES ORELLANA MANUEL',
  '4047': 'ZAMBRANO DUEÑAS MARIANO GUMERCINDO',
  '4048': 'VILLAREAL SANCHEZ OSCAR LENIN',
  '4053': 'BRAVO HEMBA RAFAEL ARTURO',
  '4054': 'TACURI MOROCHO ANGEL AUGUSTO',
  '4056': 'PASTI ZUÑIGA CARLOS GUILLERMO',
  '4059': 'MUÑOZ MARTINEZ WELLINGTON',
  '4061': 'SANTANA RIOS HOMERO POMERIO',
  '4064': 'SALAZAR LARA REGULO SANDINO',
  '4065': 'ANDRADE NORIEGA JUAN FRANCISCO',
  '4067': 'ICAZA DELGADO IDELFONSO JAVIER',
  '4068': 'ROMERO MARTINEZ RICARDO',
  '4072': 'ALVARADO VELEZ JORGE EDISON',
  '4076': 'RUIZ GOMEZ JORGE STALIN',
  '4080': 'LOPEZ OJEDIS AMARILDO ERNESTO',
  '4083': 'TIGSI NAULA WALTER OSWALDO',
  '4086': 'PEÑALOZA PAUCAR ALVARO LENIN',
  '4090': 'MENDOZA MERINO PABLO RAFAEL',
  '4091': 'JIMENEZ SOLIS WILLIANS SEGUNDO',
  '4102': 'BRAVO BRAVO ANTONIO LEONARDO',
  '4109': 'TAGLE GONZALEZ PATRICIO MELITON',
  '4118': 'MAYORGA PEÑAFIEL LUIS GERARDO',
  '4120': 'SANTILLAN YANCE JORGE FAUSTO',
  '4121': 'DELGADO LOPEZ ROY ALFONSO',
  '4131': 'GUILLEN CHOEZ CRUZ ISAIAS',
  '4133': 'PEÑARANDA BRITO SEGUNDO',
  '4134': 'ALCIVAR GARCIA JOSE CARLOS',
  '4135': 'NOBOA BARRENO EFRAIN ISAIAS',
  '4138': 'VILLAMAR CARPIO JORGE ABEL',
  '4141': 'ROJAS LEON FLAVIO MANUEL',
  '4142': 'BARRAGAN VERA JORGE LUIS',
  '4143': 'RENTERIA CELI EDGAR ADAN',
  '4144': 'SUAREZ YLLESCAS LUIS FRANKLIN',
  '4152': 'RIVAS BUENO JUAN BAUTISTA',
  '4153': 'RUIZ RODRIGUEZ JULIO ROLANDO',
  '4154': 'MORA COPO JOSE WALBERTO',
  '4155': 'HERNANDEZ ALVAREZ GIOVANNY',
  '4161': 'CASTRO VERA FIDEL ELIAS',
  '4163': 'TORRES CARRIEL UBALDO MAURICIO',
  '4164': 'NARVAEZ CHIRIBOGA GUSTAVO',
  '4168': 'RIVERA PALMA GUILLERMO LAUTARO',
  '4169': 'CALI GONZALEZ JOSE OSWALDO',
  '4170': 'PEÑA BURGOS AQUILES ANTONIO',
  '4171': 'ONOFRE GARCIA ENRIQUE JONNY',
  '4176': 'LEDESMA ORTEGA JOSE LUIS',
  '4179': 'CABRERA RAMOS JAIME AQUILES',
  '4185': 'AGUIRRE ARCOS ALEJANDRO',
  '4197': 'MACIAS PAZMIÑO RUBEN ARTURO',
  '4199': 'ALCIVAR ASTUDILLO OSWALDO',
  '4200': 'VILELA ZAMBRANO KENEDY ANTONIO',
  '4207': 'LITARDO PACHECO WILLIAM',
  '4209': 'PICO JUNCO SALES EDISON',
  '4217': 'ARAUS CUJILAN MILTON ROSENDO',
  '4224': 'PACHECO VILLEGAS JOSE MIGUEL',
  '4226': 'MONCERRATE MENDEZ MIGUEL',
  '4227': 'MORALES MARIN ABEL MIGUEL',
  '4230': 'MERELO SALVATIERRA INOCENTE ANTONIO',
  '4236': 'MARIDUEÑA JIMENEZ ABEL SALOMON',
  '4240': 'BRAVO ESTRADA VICENTE SANTIAGO',
  '4258': 'PEREZ PITA LUIS EFRAIN',
  '4294': 'ARMIJO PAREDES CARLOS ABRAHAN',
  '4295': 'VISTIN MENA EDISON WASHINGTON',
  '4296': 'ENRIQUEZ MOYANO JOHN OSWALDO',
  '4297': 'VASCONEZ GUAMAN JOSE ALEJANDRINO',
  '4302': 'GUAMAN MOYON SEGUNDO PEDRO',
  '4309': 'GUASTAY MAGARISCA RAMIRO',
  '4315': 'CHUM SALTOS FRANKLIN ALBERTO',
  '4316': 'LEON JIMENEZ PAUL SANTIAGO',
  '4321': 'MAZZINI VERA JULIO ERNESTO',
  '4327': 'PAZMIÑO SALINAS RICHARD',
  '4332': 'ALFONSO ALARCON SIGIFREDO',
  '4333': 'GONZALEZ GARCIA RICARDO OLIMPO',
  '4344': 'AGUILAR CEPEDA WILMER AUBERTO',
  '4374': 'ANGUIETA COLCHA MARIO ELIECER',
  '4376': 'GUAMAN NACIPUCHA GERMAN WALTER',
  '4404': 'PINOS ZAPATA MIGUEL ANGEL',
  '4407': 'CAIZALUISA FABRE MAURO',
  '4408': 'AREVALO AREVALO KLEVER ENRIQUE',
  '4453': 'NARANJO FLORES ANGEL RUPERTO',
  '4455': 'HERRERA PUCHA LUIS SIMON',
  '4456': 'MOYA CENTENO EDGAR ALBERTO',
  '4457': 'OROZCO LLANOS HUVER RAFAEL',
  '4458': 'GARCIA ANDRADE RENE',
  '4459': 'SABANDO CHUMO OSCAR',
  '4460': 'TOBAR ABRIL JOHNNY EDWIN',
  '4462': 'VILLAGOMEZ MORETA LUIS BENIGNO',
  '4463': 'RIVAS CEVALLOS HOLGER',
  '4464': 'ACUÑA MERCHAN RIDLER',
  '4466': 'DIAZ CARDONA WASHINGTON MIGUEL',
  '4468': 'JIMENEZ MONTERO NORMAN GERARDO',
  '4469': 'FUENTES AURIA PEDRO ANTONIO',
  '4471': 'WONG LLERENA JOSE MANUEL',
  '4473': 'ALCIVAR ARAGUNDI HOLGER',
  '4474': 'MORA MURILLO LUIS',
  '4475': 'IZQUIERDO GUERRERO JULIO WENTLAND',
  '4476': 'MONTUFAR HERNANDEZ JHON',
  '4477': 'RIVERA GORDON NELSON RICARDO',
  '4478': 'GONZALEZ ANDRADE JAVIER',
  '4479': 'JARAMILLO COX ANGEL',
  '4481': 'AYALA PALMA WILLIAM',
  '4483': 'ORDOÑEZ MARÌN  ERWIN GONZALO',
  '4484': 'SAQUICELA RODAS MARTIN EUGENIO',
  '4485': 'CACERES MARIDUEÑA  JHON',
  '4486': 'JACOME SANTOS RICARDO ALBERTO',
  '4487': 'CASTRO RODRIGUEZ MILTON',
  '4488': 'GOVEA ARANA JAVIER',
  '4489': 'AREVALO VERCOLD ALEX GUILLERMO',
  '4491': 'ARIZAGA PAREDES JOSE',
  '4492': 'MARTINEZ JARAMILLO  WILLIAM',
  '4493': 'ESPINOZA AMPUERO ANGEL ALBERTO',
  '4494': 'MIELES DEL PEZO HOLGER',
  '4495': 'OROZCO GUTIERREZ  IDEL ALFONSO',
  '4497': 'TORRES PACHAY STALIN',
  '4498': 'MARIDUEÑA MUÑOZ ALONSO',
  '4499': 'ROSADO MORA NICANOR FABIEL',
  '4500': 'BONES MERCHAN XAVIER',
  '4503': 'QUINCHUELA MARTÌNEZ WALTER',
  '4504': 'BORJA ROJAS WILLIAM',
  '4505': 'PAREDES DESIDERIO JOSE',
  '4506': 'ROSERO BRAND OMAR',
  '4507': 'HEREDIA MOSCOSO JULIO',
  '4508': 'BALLADARES MACIAS JOSE EDGAR',
  '4511': 'BUSTAMANTE BUSTAMANTE JOSE LUIS',
  '4512': 'ROSALES HOLGUIN EDMUNDO',
  '4513': 'MATUTE SALINAS JUAN',
  '4514': 'PALACIOS ESPINEL JORGE GABRIEL',
  '4516': 'MINA CHICHANDE IVAN CLODOALDO',
  '4517': 'LUNA QUEZADA  JORGE SHOVANY',
  '4518': 'AVECILLA VISCARRA MARCO ABELARDO',
  '4519': 'MONTALVO NARANJO PAUL',
  '4520': 'SABAGAY GAIBOR OSWALDO',
  '4522': 'LEON CHECA MIGUEL ALFREDO',
  '4523': 'TORRES TOLEDO LUIS',
  '4524': 'CHAVEZ ABAD DENNIS',
  '4525': 'VACA MURILLO MANUEL',
  '4529': 'ESTRELLA MOGRO JAIME MARCELO',
  '4531': 'SINCHIGUANO FLORENCIA KLEVER',
  '4533': 'VERA PLAZA JULIO',
  '4534': 'YEPEZ TRIANA JORGE DANILO',
  '4535': 'LEON ALVARADO JESUS',
  '4536': 'TERAN MONTESDEOCA ABRAHAM',
  '4537': 'CHICAIZA CALLE RICHARD',
  '4538': 'ROSERO HUACON MIGUEL',
  '4539': 'BALAREZO FREIRE EDGAR MARCELO',
  '4541': 'BUENAVENTURA CEDEÑO XAVIER',
  '4542': 'PESANTES DOLTZ ALFONSO',
  '4545': 'SALINAS BARROSO MIGUEL ANTONIO',
  '4546': 'SERDAN BENITES JORGE HUMBERTO',
  '4549': 'AGUILERA RODRIGUEZ HECTOR ELOY',
  '4550': 'REYES VARGAS LUIS ALBERTO',
  '4551': 'REALPE ZAPATA GUILLERMO LENIN',
  '4552': 'MESA ALAVA DUVAL ROLANDO',
  '4553': 'GOMEZ LOPEZ CRISTOBAL DE JESUS',
  '4554': 'VILLAMARIN ROSERO LUIS GUALBERTO',
  '4555': 'BAJAÑA GARCIA FELIPE FERNANDO',
  '4556': 'CEVALLOS MEDINA HOMERO ANTONIO',
  '4557': 'ANCHUNDIA ZAMBRANO ABEL GERACIMO',
  '4558': 'BRIONES SILVA HENRY ADALBERTO',
  '4560': 'SAN LUCAS MACIAS DANIEL ANTONIO',
  '4562': 'GONZALEZ BUSTAMANTE FRANCISCO',
  '4564': 'LEON NOBOA FREDDY MANUEL',
  '4565': 'MORAN VERA FRANCISCO RUBEN',
  '4568': 'FALCONI INSUASTI JORGE ENRIQUE',
  '4569': 'MONTALVAN RENDON INOCENTE ALFREDO',
  '4571': 'ROMERO CHIRIGUAYA ANGEL',
  '4572': 'LOPEZ JARAMILLO RICHARD',
  '4573': 'VARGAS PISCO RICARDO MOISES',
  '4574': 'ZAMBRANO MONTIEL ALFREDO',
  '4575': 'ANGULO PEÑA MIGUEL BERNARDO',
  '4577': 'MICHILENA PANCHANA RONALD CRISTOBAL',
  '4578': 'PAZMIÑO MORALES VICTOR EDUARDO',
  '4579': 'PEREZ MAGALLANES ORLIN LUIS',
  '4581': 'PEÑA BURGOS RICARDO ABSALON',
  '4583': 'DUME ALCIVAR VICTOR ANTONIO',
  '4585': 'CASTELLANOS VOTTELER EDUARDO ALBERTO',
  '4586': 'SILVA MORENO ANGEL JACOBO',
  '4587': 'SERRANO ORTIZ VICTOR HUGO',
  '4588': 'VERA MENDEZ SEGUNDO ISAIAS',
  '4590': 'MORA MANJARREZ YILMER BENIGNO',
  '4591': 'CHICHANDE VARGAS JULIO JIMY',
  '4592': 'HUACON VERA FERMIN ANTONIO',
  '4594': 'NAVARRETE BARZOLA JAVIER',
  '4596': 'SCOTLAND CHERRES JOSE ANTONIO',
  '4597': 'BONE BARZOLA ROBERT ARNULFO',
  '4598': 'SANCHEZ CAUJA FREDDY ANGEL',
  '4600': 'FRUTUOSO CABRERA EDISON ALBERTO',
  '4601': 'GOMEZ ORTIZ BOLIVAR DAVID',
  '4604': 'CAÑIZARES ORTEGA ALEX JAVIER',
  '4605': 'HIDALGO TORRES MIGUEL OCTAVIO',
  '4606': 'CASTRO NAVARRO LUIS HUMBERTO',
  '4608': 'AGUILAR CABELLO OMAR NICANOR',
  '4611': 'RODRIGUEZ QUIÑONEZ SEGUNDO',
  '4614': 'FRANCO CEPEDA JIMMY GERARDO',
  '4617': 'VERA ROMERO EDGAR JEOVANI',
  '4619': 'MINDIOLAZA RENDON HENRY RAMON',
  '4620': 'GONZALEZ SOLIS ELVIS MOISES',
  '4621': 'CHAVEZ VARGAS JUAN JORGE',
  '4622': 'RIVAS BUENO CIRILO MIGUEL',
  '4623': 'JIMENEZ SOLIS GUILLERMO',
  '4624': 'ACUÑA CEVALLOS NERYS ROBERTO',
  '4625': 'FARIAS FLORES MANUEL ALEJANDRO',
  '4626': 'YEPEZ AREVALO CARLOS ESTUGART',
  '4629': 'SANCHEZ MERCHAN NELSON JESUS',
  '4630': 'FLORES LOPEZ SIXTO ARMANDO',
  '4631': 'DIAZ PLAZA FRANKLIN WALTER',
  '4632': 'NARANJO PEÑA LUIS ALBERTO',
  '4633': 'TOBAR GANCHOZO ALFREDO JAMIL',
  '4636': 'PICO LEON RODRIGO ROLANDO',
  '4637': 'BARCIA SALAZAR WILSON ARNULFO',
  '4638': 'PEÑA VILLEGAS RAFAEL ALFREDO',
  '4639': 'VELEZ ZAMBRANO GRINOLFO ROSENDO',
  '4641': 'VASQUEZ HOLGUIN MAXIMO EDUARDO',
  '4642': 'ARBELAEZ ALMEIDA JOSE CARLOS',
  '4643': 'ANGOS BALANDRA JORGE GUSTAVO',
  '4644': 'GAMARRA CHAFLA GALO GUSTAVO',
  '4645': 'BRAVO ARELLANO ENRIQUE SEGUNDO',
  '4646': 'IZQUIERDO CHIRIGUAYA CARLOS',
  '4648': 'CHAVEZ ACURIO JUAN JOSE',
  '4650': 'MOREIRA ARAUJO JOHNNY FIDEL',
  '4651': 'TROYA CONTRERAS JORGE EDUARDO',
  '4652': 'NARANJO VELASQUEZ MARIO BOLIVAR',
  '4654': 'CABRERA VERA LUCRECIO FROILAN',
  '4655': 'QUINTO GUTIERREZ JORGE',
  '4657': 'MAYA CEDEÑO FELIX HUMBERTO',
  '4658': 'SANGUÑA ZAMBRANO LUIS ALFREDO',
  '4659': 'AGUAYO BUSTAMANTE HERMY',
  '4660': 'NUÑEZ MOYANO JORGE AUGUSTO',
  '4661': 'MATAMOROS SAMANIEGO CARLOS',
  '4662': 'SUAREZ JORDAN MARIO EDUARDO',
  '4663': 'JIMENEZ NIETO JOSE IRENO',
  '4664': 'ROMERO BLACIO CARLOS ALBERTO',
  '4668': 'ARMENDARIZ ZAMBRANO KLEBER',
  '4669': 'SEMINARIO LITARDO WALTER',
  '4670': 'CONTRERAS VALENZUELA VICENTE',
  '4673': 'VILLAO MASCOTE BERNALDO ELEUTERIIO',
  '4674': 'CASTRO CARRANZA DUWIN STALIN',
  '4675': 'VEINTIMILLA ALVAREZ ANGEL',
  '4676': 'MACIAS HERRERA OSWALDO ALFREDO',
  '4677': 'HERRERA RODRIGUEZ MIGUEL ANGEL',
  '4680': 'GARCIA VARGAS IGNACIO ADOLFO',
  '4681': 'SUAREZ GARCIA WASHINGTON',
  '4682': 'NEGRETE FERNANDEZ LUIS ALBERTO',
  '4683': 'VARGAS VERA JOHN DAVID',
  '4684': 'BAILON PEREZ WINNEL JOHNNY',
  '4685': 'LOZANO GARCIA TITO BOLIVAR',
  '4686': 'VARGAS ANDALUZ HENRRY WILLIAMS',
  '4687': 'CANALES GUEVARA EFREN ANIBAL',
  '4688': 'ALVARADO BARREZUETA LUIS',
  '4689': 'ALMEIDA PARDO JAVIER RAMIRO',
  '4691': 'CAICEDO CABELLO AUGUSTO',
  '4692': 'GUAMAN SORIA EDWIN GONZALO',
  '4693': 'PEREZ FUENTES  RAUL',
  '4695': 'MONAR PONCE JULIO CESAR',
  '4696': 'MENDOZA MERINO VICTOR MANUEL',
  '4697': 'GARCIA PARRAGA NEUTO RAFAEL',
  '4699': 'CRUZ VEGA RAUL MANUEL',
  '4700': 'GARCIA OLVERA HECTOR ANTONIO',
  '4703': 'TORRES SEGURA PEDRO',
  '4704': 'DELGADO ARIAS FIDEL SIMON',
  '4705': 'VELEZ MENDOZA JIMMY BELISARIO',
  '4707': 'CALDERON CHOEZ PEDRO GEOVANNY',
  '4708': 'DOMINGUEZ RIVADENEIRA FREDDY',
  '4710': 'MACIAS ANDRADE FLORESMILO',
  '4711': 'ASTUDILLO ORELLANA HUGO',
  '4714': 'PITA PAZMIÑO FREDDY GREGORIO',
  '4715': 'RAMOS FRANCO ALEX ALEJANDRO',
  '4717': 'TEJADA VALDEZ FROILAN',
  '4719': 'CHAVEZ SAMANIEGO HECTOR ANIBAL',
  '4721': 'PELAEZ MARQUEZ MARIO EMILIO',
  '4723': 'SAMANIEGO SAMANIEGO OSCAR',
  '4724': 'MENDOZA GUERRERO JAIME VICENTE',
  '4725': 'BAÑO GARCES GUILLERMO WILLIAM',
  '4727': 'ALARCON LOOR RICHARD WILSON',
  '4729': 'ARELLANO PINELA GREGORIO',
  '4730': 'JIMENEZ SOTO JUAN',
  '4731': 'PUENTE TENEZACA JOSE',
  '4734': 'RUIZ GARCIA PEDRO',
  '4735': 'VIZUETA SAMANIEGO JHONNY',
  '4736': 'PALMA DIAZ JHONNY',
  '4737': 'MORA MORA GUIDO JAVIER',
  '4738': 'RODRIGUEZ LINDAO SANTO',
  '4739': 'PITA PIGUAVE ANDRES',
  '4740': 'GARCIA TRUJILLO ABRAHAM',
  '4741': 'MERA BRITO JOSE',
  '4742': 'GONZALEZ BAJAÑA JUAN',
  '4743': 'MOLINA VERGARA GERSON',
  '4745': 'CRESPO ZORRILLA MARIO ANTONIO',
  '4746': 'PICO REYES JOSE JOSE',
  '4748': 'RIVAS RONQUILLO VICTOR ANTONIO',
  '4749': 'MARTILLO SANCHEZ JOSE',
  '4750': 'VITERI MORENO PEDRO',
  '4752': 'BERMEO TOALA JHON WILSON',
  '4753': 'MENDIETA MENDEZ GALO',
  '4754': 'ARTEAGA  JONNY HERNAN',
  '4757': 'GUERRERO BARRETO RUBEN',
  '4759': 'CASTILLO BURGOS WASHINGTON',
  '4760': 'ESPINOZA BAQUERIZO RICHARD',
  '4761': 'AYALA MARIDUENA ROGER',
  '4762': 'AVELINO DIAZ MARCOS',
  '4763': 'RIOS SINALUISA JULIO ALFREDO',
  '4764': 'VASCONEZ ZURITA PEDRO',
  '4765': 'MARURI MORAN CIPRIANO',
  '4766': 'RUIZ HIDALGO WALTER',
  '4767': 'JARA DOMINGUEZ JORGE',
  '4768': 'BRIONES ANDRADE FRANCISCO',
  '4769': 'BARRERA ALCIVAR JOSE',
  '4770': 'SILVA CASTILLO MICHAEL',
  '4771': 'SABANDO CARRIEL JORGE MANUEL',
  '4772': 'CASTILLO CAMPO PEDRO',
  '4774': 'HUILCAPI SANCHEZ LUIS',
  '4775': 'LARA REYES FAUSTO',
  '4777': 'VALAREZO BRIONES CIRO',
  '4778': 'CHAVEZ SOLIS PABLO',
  '4779': 'CANTOS CORDOVA DARWIN',
  '4780': 'VARGAS MUNOZ BENANCIO',
  '4781': 'ZUMBA ASTAIZA VICENTE',
  '4782': 'HIDALGO SILVA JUAN',
  '4784': 'MARTINEZ LOPEZ PEDRO',
  '4785': 'BAJAÑA RUGEL FRANCISCO',
  '4786': 'VALENCIA RODRIGUEZ FRANKLIN',
  '4787': 'FAJARDO ARZUBE FREDDY',
  '4788': 'LAZ LOPEZ HUGO ELIAS',
  '4789': 'CORONEL ZUNIGA JOFFRE',
  '4790': 'MOREIRA AGUAYO JULIO',
  '4792': 'NEVAREZ LOZA JAVIER',
  '4793': 'YUNAPANTA CUNALATA WASHINGTON',
  '4795': 'LUCIO GAIBOR ANIBAL',
  '4796': 'ORTIZ VELIZ JOHNNY JAVIER',
  '4798': 'MENDOZA MENDOZA RAMON',
  '4799': 'CABRERA BARRIONUEVO JUAN',
  '4801': 'BURGOS BOZA PEDRO',
  '4802': 'PACHECO CENTENO VICTOR',
  '4804': 'MONAR PONCE JULIO DANILO',
  '4805': 'JURADO VARGAS ANGEL',
  '4806': 'BERMUDEZ REYES LEONARDO',
  '4808': 'BURGOS CEDENO ROMULO',
  '4810': 'SALAVARRIA GOYA WALTER',
  '4817': 'BRAVO CADENA FRANKLIN',
  '4818': 'AYALA AGUIRRE EDISON',
  '4819': 'RUIZ VELOZ EDISON',
  '4820': 'BELLO ALCIVAR UBALDO',
  '4821': 'VILLACIS MONCADA JACINTO',
  '4822': 'SANCHEZ VARGAS ERWIN',
  '4823': 'CEDEÑO CARPIO LEONIDAS',
  '4825': 'GAIBOR PAREDES FRANKLIN',
  '4826': 'ASQUI VALDEZ LUIS',
  '4828': 'TORRES ALVARADO JOSE LUIS',
  '4829': 'MUÑOZ MOREIRA VICTOR',
  '4831': 'ALAVA PLUAS ROBERTO',
  '4833': 'SILVA BAÑO GEOVANY AMADO',
  '4834': 'SAMANIEGO VASQUEZ LUIS ROBERTO',
  '4835': 'MOYOTA GADVAY MANUEL ALCIDES',
  '4836': 'SAMANIEGO ESPINOZA NELSON',
  '4838': 'FERNANDEZ ESPINOZA HUMBERTO',
  '4840': 'VALDEZ QUIJIJE JORGE ALBERTO',
  '4841': 'LUNA VIEJO BAIRON ABRAHAN',
  '4842': 'TOMALA VILLON KLEBER ARNALDO',
  '4843': 'MORETA ESPINOZA CESAR JACINTO',
  '4845': 'CAMINO PAREDES LISTER JAVIER',
  '4846': 'CANO NARANJO DARWIN ENRIQUE',
  '4847': 'HERRERA ALCIVAR ENRIQUE ALFONSO',
  '4848': 'DEMERA BAILON JOSE ALFREDO',
  '4849': 'ROMERO ALCIVAR LIBIO MANUEL',
  '4851': 'VILLAMAR HOLGUIN ALEJANDRO',
  '4852': 'ESPINOZA SALAZAR MARLON VICENTE',
  '4853': 'ERAZO OLAYA RENE JAVIER',
  '4854': 'ZAMBRANO LOOR ROBERT EDUARDO',
  '4856': 'GARCIA YEPEZ JOSE ALBERTO',
  '4857': 'BURGOS ALVARADO BRADEN',
  '4859': 'DELGADO TUMBACO FRANKLIN WILMAN',
  '4860': 'OÑATE SANCHEZ LINO FABIAN',
  '4861': 'TOMALA TOAZA CARLOS VICENTE',
  '4862': 'RODRIGUEZ QUIMIS JOSE GEOVANNY',
  '4864': 'CONTRERAS ROMERO TEOFILO',
  '4865': 'AVILA VERA LUIS PATRICIO',
  '4866': 'ORTIZ MORETA JOSE ISAIAS',
  '4868': 'ROSADO SELLAN MARCELO ALBINO',
  '4869': 'MARTINEZ JIMENEZ CARLOS RAFAEL',
  '4870': 'BUÑAY GUANGA LUIS ALBERTO',
  '4871': 'ANGULO ALVAREZ BOSCO ROMMEL',
  '4872': 'RIVAS PONCE GALO MIGUEL',
  '4873': 'AGUI ALVAREZ ARMANDO ARTURO',
  '4875': 'GRANDA TRELLES JORGE LUIS',
  '4877': 'ANDRADE MOROCHO CARLOS DARWIN',
  '4878': 'BAÑO GARCIA EDISON GERARDO',
  '4879': 'HURTADO ABARCA HENRY FABIAN',
  '4880': 'VERA MARTINEZ SAMUEL HONORIO',
  '4882': 'VELOZ JARAMILLO GEOVANNY',
  '4883': 'YUBI ESPINOZA WILMER ALBERTO',
  '4884': 'VITER VALENCIA DAVID ARMANDO',
  '4886': 'CHICAIZA PEÑALOZA VICTOR',
  '4888': 'ARISTEGA ALVARADO TAURINO',
  '4889': 'BRIONES SILVA JOSE MANUEL',
  '4890': 'VILLACRES SAMANIEGO WOLTER',
  '4891': 'LESCANO PONCE RICARDO OSWALDO',
  '4892': 'SEGURA PACHAY JOSE DANIEL',
  '4895': 'AÑAZCO AÑAZCO NELSON ENRIQUE',
  '4896': 'ESPINOZA ORTIZ NIXON DIEGO',
  '4897': 'MARTINEZ LOPEZ JORGE DANIEL',
  '4899': 'LOPEZ ARREAGA JOSE ALFREDO',
  '4900': 'ARMENDARIZ ZAMBRANO GERMAN',
  '4902': 'MAYORGA PENA CESAR MISAEL',
  '4903': 'GUILLEN JIMENEZ HOLGER OMAR',
  '4906': 'MUÑOZ MERELO NIXON MAXIMO',
  '4908': 'ACOSTA SALAZAR EDDY GERMAN',
  '4909': 'BAÑO GARCIA IVAN GONZALO',
  '4910': 'CHICHANDA REINEL JAVIER EDUVID',
  '4911': 'COBEÑA CAMACHO WALTER JESUS',
  '4912': 'OROZCO GUERRON HUGO ENRIQUE',
  '4913': 'JIMENEZ CARRANZA EVERALDO',
  '4914': 'RONQUILLO VILLAREAL KLEVER',
  '4915': 'VALAREZO VASQUEZ EDWIN ABDALA',
  '4916': 'SEGOVIA PARRA GUILLERMO JUNIOR',
  '4917': 'SALAZAR LARA VICTOR HUGO',
  '4918': 'ROMAN QUINTO EUCLIDES ROLANDO',
  '4919': 'SERNA ROMERO GALO FERNANDO',
  '4920': 'SANCHEZ TIRAPES EFREN YONNY',
  '4921': 'ZAMBRANO CHINIZACA WASHINGTON',
  '4924': 'MORAN MEJIA JUAN HUMBERTO',
  '4925': 'LOZANO SALAZAR ALFONSO ELIAS',
  '4927': 'INCA LOPEZ VICTOR',
  '4928': 'HIDALGO RUIZ SAUL JOFFRE',
  '4931': 'VITERI MORENO HECTOR JAVIER',
  '4932': 'MOREIRA CHAVEZ DARWIN MEDARDO',
  '4934': 'QUITO ASQUI NESTOR ANIBAL',
  '4935': 'VILLON JORDAN VICENTE',
  '4936': 'CARDENAS TAPIA DARWIN HOLGER',
  '4937': 'ERAZO MUÑOZ EDGAR CECILIO',
  '4938': 'ZUÑIGA MAGALLANES OMAR',
  '4939': 'GARCES OÑATE IVAN ALEX',
  '4940': 'NARANJO CONTRERAS ALEJANDRO',
  '4942': 'GAYBOR PIZA ABEL IVAN',
  '4943': 'CAIZA ASQUI CARLOS VINICIO',
  '4944': 'QUISPE GUAMAN CESAR',
  '4945': 'CHINILLI LOPEZ PEDRO PABLO',
  '4946': 'MACIAS TOBAR JAVIER',
  '4947': 'ALTAMIRANO HUACON VICTOR',
  '4948': 'CABRERA ZHAGNAY JUAN DERWIN',
  '4951': 'RODAS SOTO RENE RODOLFO',
  '4952': 'PEÑA CAMPOVERDE JESUS',
  '4954': 'CEREZO CERVANTES DENIS EDGAR',
  '4955': 'HERNANDEZ BARROSO EDISON EFREN',
  '4956': 'GOMEZ GOMEZ STALIN JAVIER',
  '4958': 'MACIAS CABALLERO LORENZO',
  '4959': 'BARRETO SALTOS PETER DARWIN',
  '4961': 'PARRAGA ZAMBRANO EDGAR EUGENIO',
  '4962': 'BERMEO TOALA HENRY RICHARD',
  '4963': 'BASTIDAS MARTINEZ NERY NATHAHEL',
  '4965': 'SANTILLAN CEQUEIRA GERMAN DE',
  '4967': 'RICO RIVERA JUAN ANTONIO',
  '4968': 'JONES VASQUEZ FELIX AVELINO',
  '4969': 'JURADO VARGAS VICTOR HUGO',
  '4971': 'CARRASCO ORDOÑEZ HENRY POLIBIO',
  '4973': 'AGUIRRE RUIZ JHON STALIN',
  '4974': 'NAVARRO ZAMBRANO HUGO',
  '4975': 'LOPEZ PEÑA NAY RADANES',
  '4977': 'CHONILLO DIAZ WALTER BENIGNO',
  '4978': 'JIMENEZ SESME ALEX IVAN',
  '4979': 'MOREIRA CEDEÑO EDUARDO',
  '4980': 'YEPEZ VERA GALO LORENZO',
  '4981': 'ASTUDILLO DE LA CUADRA RAUL ENRIQUE',
  '4983': 'BORBOR ZAPATA JHONNY ROBERTO',
  '4984': 'JARAMILLO MAYESA YANDRY OSWALDO',
  '4985': 'GARCIA CEDEÑO EDISON',
  '4986': 'SANCHEZ LOPEZ BOLIVAR IDILIO',
  '4987': 'OCAÑA SARMIENTO LUIS FABRICIO',
  '4988': 'GOYA CEREZO JOSE LUIS',
  '4989': 'MIRANDA TORRES ALBERTO',
  '4991': 'ROGGIERO AGUIRRE JAVIER',
  '4992': 'SOLORZANO VILLAGOMEZ HUGO FRANCISCO',
  '4995': 'ARREAGA MARIDUEÑA JULIO CESAR',
  '4996': 'VARGAS CHICHANDE NESTOR SAUL',
  '4999': 'INTRIAGO MACIAS STALIN',
  '5000': 'CASTELO MEDIAVILLA MILTON',
  '5001': 'CAMINO PAREDES JHONNY DAVID',
  '5002': 'BONE CHILA JESUS PEDRO',
  '5003': 'CRESPO MORA WINVER JOSEPH',
  '5004': 'RODRIGUEZ ESCALA ROMNY XAVIER',
  '5005': 'CEDEÑO NAVIA IVAN',
  '5006': 'GAMBOA YUCAILLA IVAN GIOVANNI',
  '5007': 'MOTA LOY JHON LEONEL',
  '5008': 'VARGAS MACIAS VICTOR IVAN',
  '5009': 'SORIANO ROCHA GENARO DANIEL',
  '5011': 'TORRES PILLIGUA MARCOS GABRIEL',
  '5098': 'BRIONES NAVARRETE CRISTHIAN GUILLERMO',
  '5100': 'PLUAS BARCIA JUAN JOSE',
  '5101': 'GUIRACOCHA PERALTA RICARDO JAVIER',
  '5102': 'CASTRO PARRALES ALEX IVAN',
  '5103': 'MATUTE PETROCHE VICTOR HUGO',
  '5104': 'INTRIAGO BURGOS JIMMY FERNANDO',
  '5106': 'DUME ALCIVAR ALEX ENRIQUE',
  '5107': 'BENAVIDES SANTOS SANDY WIMPER',
  '5108': 'RODRIGUEZ BAYAS JUAN SALVADOR',
  '5109': 'VELEZ PONCE MARCOS AUGUSTO',
  '5110': 'IBARRA PEREZ JAVIER ALBERTO',
  '5111': 'RIZZO LEON BYRON OMAR',
  '5112': 'MANCERO CARDENAS JIMMY RAFAEL',
  '5113': 'ARREAGA FRANCO RAUL ALFREDO',
  '5115': 'CHIQUITO JUSTILLO WASHINGTON GABRIEL',
  '5116': 'ARISTEGA ORTIZ JIMMY EDUARDO',
  '5118': 'MORA VELIZ JHONY ROBERTO',
  '5120': 'VIZUETA DAVILA JOSE ROBERTO',
  '5121': 'ROBALINO PAZMIÑO VICTOR EMILIO',
  '5122': 'CORDOVA RAMOS LUIS HUMBERTO',
  '5124': 'VASCONEZ BUSTILLOS JULIO ESTALIN',
  '5125': 'SALAZAR ORTEGA CRISTHIAN DARWIN',
  '5126': 'BAJAÑA GOMEZ WASHINGTON ALONSO',
  '5127': 'LEON ANDRADE CESAR OCTAVIO',
  '5128': 'ESCOBAR FLORES OWEN JENRY',
  '5129': 'BORJA ROJAS DARWIN RODRIGO',
  '5130': 'JIMENEZ PANCHANA FABIAN GERHARDY',
  '5132': 'MORAN LOZANO JOSE VICENTE',
  '5133': 'JIMENEZ RECALDE JOHNNY HENRY',
  '5134': 'ROBALINO PAZMIÑO WILLINGTON ALEXIS',
  '5135': 'VEINTIMILLA ESCALA JOSE CRISTHIAN',
  '5137': 'SABANDO CHUMO RAMON LEONARDO',
  '5140': 'GUERRERO VELIZ GUILLERMO RAFAEL',
  '5141': 'INTRIAGO MACIAS JHON EDUARDO',
  '5142': 'SANTAMARIA SALAZAR RAFAEL ALFONSO',
  '5143': 'VASQUEZ VELASTEGUI JAIRO GEOVANNY',
  '5144': 'ROJAS MURILLO CARLOS ALBERTO',
  '5146': 'CASAN AYERVIDE FRANKLIN GUSTAVO',
  '5147': 'TORRES HIDALGO JONATHAN FERNANDO',
  '5400': 'LAGOS REINOSO  GUSTAVO',
  '5402': 'UNAMUNO MEJIA  ADEMAR',
  '5403': 'MANZO VELIZ  ISAAC',
  '5404': 'BARRERA ANDOCILLA EDISON',
  '5405': 'PEREZ COELLO  DARWIN',
  '5406': 'MUÑOZ FELIX   RAMON',
  '5407': 'MOREIRA HAZ  HENRY ANTONIO',
  '5408': 'CEVALLOS GUINGLA CARLOS',
  '5409': 'JACOME ESTRELLA  VICTOR',
  '5411': 'SILVA FRANCO  JAIME',
  '5412': 'INTRIAGO BURGOS  STALIN',
  '5413': 'GALEAS CRIOLLO CHRISTIAN',
  '5414': 'ARGUELLO BAJAÑA  DANIEL',
  '5415': 'MOREIRA FIGUEROA FERNANDO',
  '5416': 'ROMERO MEJIA  MARCOS',
  '5417': 'CEDEÑO ULLAURI  ANGEL',
  '5418': 'CABANILLA MONSERRATE EDUARDO',
  '5420': 'SUAREZ MUNIZAGA  DARIO',
  '5421': 'SUQUILLO GORTAIRE GERMAN',
  '5422': 'FLORES SAA EDDY',
  '5423': 'SARES CAMPOVERDE  DELMER',
  '5424': 'NAVAS ROMERO  JOSE',
  '5425': 'ROBEN LOOR  AARON',
  '5426': 'JACOME PEÑA  RONALD',
  '5427': 'CAICEDO LOPEZ  LUIS',
  '5428': 'IBARRA AMAGUANA  ANGEL',
  '5429': 'VIDAL COBEÑA FERNANDO',
  '5430': 'CORDOVA MORALES  FELIX',
  '5432': 'MEDINA CAAMAÑO  JOHNNY RAMON',
  '5433': 'ANDRADE ESPINOZA ANGEL',
  '5631': 'VARGAS MARIÑO GIOCONDA ALEXANDRA',
  '5632': 'CORTES JACOME ROSANA PILAR',
  '5633': 'VARGAS COELLO HIPATIA MAGDALENA',
  '5634': 'LOPEZ MOLINA JANNET MARIBEL',
  '5635': 'SILVA CARPIO ROSARIO MARLENE',
  '5636': 'ZAVALA MORA DORIS MARIUXI',
  '5637': 'CASTAÑEDA FIGUEROA IDISES LIZ',
  '5638': 'VALENZUELA PLUAS LINDA AMANDA',
  '5640': 'BRAVO GUERRERO MARIA JOSE',
  '5641': 'MONTERO GARCIA CARMITA ISABEL',
  '5642': 'CARDENAS NAVARRO MAYRA FERNANDA',
  '5643': 'MARTINEZ GRUEZO  FLOR DOMENICA',
  '5644': 'PEÑA ALVAREZ ERICKA YULIANA',
  '5645': 'CARDENAS CABRERA CAROLINA DEL CARMEN',
  '5646': 'FEY GONZALEZ CINTHYA TERESA',
  '5647': 'FRANCO DEL PEZO VERONICA NATHALY',
  '5648': 'PEÑA NEGRETE MIRNA CECILIA',
  '5649': 'MERCHAN ZHUNE YADIRA ALEXANDRA',
  '5650': 'CASTAÑEDA CALOPIÑA CAROL FERNANDA',
  '5651': 'MORAN PLUAS ROSA MARCELA',
  '5652': 'MEDINA CAAMAÑO JENNIFER YBSEL',
  '5653': 'NAVARRETE TORRES DENISSE LISETTE',
  '5654': 'ARELLANO CEDEÑO JUANA CECIBEL',
  '5655': 'RODRIGUEZ AVECILLA EVELYN ANABEL',
  '5656': 'LOZANO BENITEZ VERONICA LUCIA',
  '5657': 'CAMPUZANO SAENZ AMBAR IRENE',
  '5658': 'ECHEVERRIA GRANIZO VERONICA PAOLA',
  '5659': 'RENTERIA CABEZAS MARICELA TATIANA',
  '5660': 'CARPIO DELGADO JOHANNA MIRELLY',
  '6060': 'OÑATE CERVANTES ERICK',
  '6062': 'MONTALVAN ESPINOZA JUAN',
  '6063': 'ALVAREZ CHAMBA FREDDY',
  '6064': 'SAULA PLAZA MICHAEL',
  '6065': 'GUEVARA FREIRE MARIO SANTIAGO',
  '6066': 'SEPA PALACIOS ROLANDO',
  '6067': 'VERA MORAN ALDO ROBERTO',
  '6068': 'TOVAR ANDRADE DIEGO',
  '6070': 'GALLEGOS RICAURTE JUAN PABLO',
  '6071': 'MERA CRESPO MARLON',
  '6072': 'HOPPE ZAMBRANO HUGO',
  '6074': 'BUSTAMANTE CEPEDA ISRAEL',
  '6075': 'CORTEZ MORALES JORGE',
  '6076': 'MARTINEZ NARVAEZ SLEYDER',
  '6077': 'RAMIREZ BRAVO DANNY',
  '6078': 'RODRIGUEZ GONZABAY JONATHAN',
  '6080': 'PALACIOS MACIAS HENRY',
  '6081': 'ROBLES BALAZ CHRISTIAN',
  '6082': 'CEVALLOS GUINGLA DAVID',
  '6083': 'MOREIRA HAZ  EDWIN',
  '6084': 'BENAVIDES SANTOS WILMER',
  '6085': 'GARZON PAREDES SANDRO',
  '6087': 'ONOFRE MARTINEZ ANDRES',
  '6088': 'SANCHEZ LLANOS EDISON',
  '6090': 'LOPEZ FLORIL BYRON JONATHAN',
  '6092': 'ROGGIERO AGUIRRE ERICK',
  '6093': 'MANZANO RAMOS JORGE',
  '6094': 'VALENCIA ORELLANA JHONNY',
  '6095': 'MOREIRA PURUNCAJAS JONATHAN',
  '6097': 'UVIDIA FARIÑO IVAN',
  '6098': 'MONTERO RUILOVA JUAN',
  '6099': 'ASPIAZU MALDONADO ERIK',
  '6100': 'PILALO COELLO RONALD',
  '6101': 'NARVAEZ GUARACA HENRY',
  '6102': 'MAXI PEHOVAZ CESAR MIGUEL',
  '6103': 'BAÑOS ARMIJOS JAIRO MOISES',
  '6104': 'GUAMAN VALAREZO CESAR',
  '6105': 'CARRILLO FALCONI PAULO',
  '6106': 'CAMPUZANO SAENZ EDUARDO',
  '6107': 'VELIZ VULGARIN DAVID',
  '8085': 'CUÑAS MAYORGA BRYAN JOSE',
  '8086': 'SOLIS ZHAGUI ANGEL JHONATAN',
  '8087': 'RODRIGUEZ CANDELARIO BRENDA SILVANIA',
  '8088': 'COLOMA PARDO EMELIA ISABEL',
  '8089': 'BRITO MENDOZA JOHN ARIEL',
  '8090': 'VERA VERA VIKY VIVIANA',
  '8091': 'CABRERA HERRERA NESTOR ADALBERTO',
  '8092': 'ALTAMIRANO GUZMAN ARACELY ALEXANDRA',
  '8093': 'MERA CRESPO ROSALVA GABRIELA',
  '8094': 'BELLOLIO MERO MANUEL DE JESUS',
  '8095': 'BURGOS MENDOZA CARLOS ALFREDO',
  '8096': 'CAIXALUISA ARREAGA JHONATAN JAMPIER',
  '8097': 'MONTENEGRO VARGAS OSWALDO ISRAEL',
  '8098': 'CAMBA ROCHA WALTER ANDRES',
  '8099': 'ULLON CHACON MADELYN YANINA',
  '8100': 'QUIROZ ORTIZ DIEGO FERNANDO',
  '8101': 'ALVARADO GOMEZ  LUIS ALFREDO',
  '8102': 'ARRIAGA MORALES RONNIE MARCELO',
  '8103': 'MENDOZA ANGAMARCA ISRAEL MOISES',
  '8104': 'BATIOJA CHAVEZ ALEXYS BEATRIZ',
  '8105': 'MEJIA ROMERO JAZMIN STEFANIA',
  '8106': 'BRAVO JIMENEZ WASHINGTON RICARDO',
  '8107': 'VELASCO HERRERA FERNANDO ISRAEL',
  '8108': 'ESTEVEZ PINO JOSE STALYN',
  '8109': 'HENRIQUEZ TOMALA HERNAN FERNANDO',
  '8110': 'SAMANIEGO CATUTE LISBETH JACQUELINE',
  '8111': 'TOVAR ANDRADE JOSE CARLOS',
  '8112': 'MIRANDA RAMOS GALO JESUS',
  '8113': 'BARRERA SARMIENTO NILA STEFANIA',
  '8114': 'LOPEZ PAZ FABRICIO AGUSTIN',
  '8115': 'GARCIA GUERRERO ALAN GUSTAVO',
  '8116': 'OLMEDO FERRUZOLA FERNANDO XAVIER',
  '8117': 'CANEPA CABALLERO LUIS ANTONIO',
  '8118': 'CASTRO CASTRO LIVINSTON STALIN',
  '8119': 'LARREA CHAVEZ GIANNY FERNANDA',
  '8120': 'SILVA AVILA RICARDO ANTONIO',
  '8121': 'RUGEL GARCIA PAUL VIRGILIO',
  '8122': 'CHIRIBOGA MARTILLO JENNY LISSETTE',
  '8123': 'FUENTES MORAN LIA DEL ROCIO',
  '8124': 'COTERA CABRERA LISSETTE ELIZABETH',
  '8125': 'VERA ROSADO JOSE PATRICIO',
  '8126': 'PACHECO MENDOZA NELSON DANIEL',
  '8127': 'SALVATIERRA MOREIRA MICHAEL MANUEL',
  '8128': 'PADILLA MENENDEZ GEOVANNY ANDRES',
  '8129': 'DIAZ ZAMBRANO EDGAR FABIAN',
  '8130': 'ALCIVAR MONTECE YALITZA VIVECA',
  '8131': 'BAJAÑA SARMIENTO WALTER ENRIQUE',
  '8132': 'BRITO ZERNA JOSE ENRIQUE',
  '8133': 'RAMIREZ VILLALVA RONALD JACINTO',
  '8134': 'FREIRE GUILLEN MARIA JOSE',
  '8135': 'JARA MACIAS MARIA JOSE',
  '8136': 'SANTILLAN MORA JAYRON ALFREDO',
  '8137': 'SALAZAR ORTIZ FRANCISCO XAVIER',
  '8138': 'CEDEÑO CHAVEZ JUAN ANDRES',
  '8139': 'OLVERA CAMBA HILARIO LEANDRO',
  '8140': 'GUEVARA GUEVARA JULIO CESAR',
  '8141': 'PULIDO PALACIOS ALEXI FABIAN',
  '8142': 'CALDERON PLUA BELEN STEFANY',
  '8143': 'MIÑO RENGIFFO NELSON JAVIER',
  '8144': 'ALARCON ORTIZ ALEX FELIPE',
  '8145': 'PIEDRA ROSALES PAOLA SUGEY',
  '8146': 'CASTRO QUISPE GILDA ELIZABETH',
  '8148': 'JUPITER ESPINOZA ORLEY JESUS',
  '8149': 'SAMANIEGO ZAMORA JHON DANIEL',
  '8150': 'JARRIN MORAN JOHANNA JAZMIN',
  '8151': 'DUARTE AVILES KAREN LETICIA',
  '8152': 'CUYAN CHIMBO ALVARO DAVID',
  '8153': 'BARRETO ESCOBAR DIEGO ALEJANDRO',
  '8154': 'SILVA VIVAR DANIEL ROBERTO',
  '8155': 'CALDERON JURADO CESAR ANDRES',
  '8156': 'JUBILEZ CHACON JACQUELINE CECIBEL',
  '8157': 'ANDALUZ MARIÑO ANTONIO ALFONSO',
  '8158': 'QUIÑONEZ ALCIVAR ISABEL MARIA',
  '8159': 'MENDOZA RUMIGUANO ALEXIS JAVIER',
  '8160': 'GUAMAN CARRILLO ALEX FABIAN',
  '8161': 'ALVEAR LOPEZ INES MARIUXI',
  '8162': 'ZUÑIGA RODRIGUEZ PEDRO GUILLERMO',
  '8163': 'NAVARRO MARIDUEÑA WASHINGTON WILFRIDO',
  '8164': 'PLAZA GUERRERO WLADIMIR ALEXANDER',
  '8165': 'MALDONADO VINUEZA MIGUEL ANGEL',
  '8166': 'PONCE ROSALES VICTOR GABRIEL',
  '8167': 'CAMINO QUEZADA FLOR ELIZABETH',
  '8168': 'UVIDIA HERRERA MARIA DE LOS ANGELES',
  '8169': 'TIGRE SANCHEZ DIANA ELIZABETH',
  '8170': 'MACANCELA PRADO ANGEL ESTEBAN',
  '8172': 'ALCIVAR VILLAMAR GERARDO ADRIAN',
  '8173': 'JARAMILLO TORRES STEVEN ENRIQUE',
  '8174': 'CASTILLO GUERRERO KATTY ALEXANDRA',
  '8175': 'ALVARADO ARAUJO CAROLINA PAOLA',
  '8176': 'BASANTES PACHUCHO SAMUEL MATEO',
  '8177': 'SANUNGA TOTOY JEANNETTE ELIZABETH',
  '8178': 'FALCONES CAICEDO KEVIN MAURILIO',
  '8179': 'CARPIO CASTRO DIEGO JAVIER',
  '8180': 'GUTIERREZ POVEDA JAVIER ROLANDO',
  '8181': 'HIDALGO SANCHEZ VANESSA LILIANA',
  '8182': 'BARROS UBILLA DILON ISRAEL',
  '8183': 'FERNANDEZ MIÑO LUIS JAVIER',
  '8185': 'MORETA MONTOYA LEONARDO ANDRES',
  '8186': 'MOYANO GUEVARA ANDREA ESTEFANIA',
  '8187': 'CEVALLOS HOLGUIN MARIO LUIS',
  '8188': 'ARIAS PACHECO HOMERO MAURICIO',
  '8189': 'MEDINA GUAMAN MAYRA ALEJANDRA',
  '8190': 'MACIAS ROJAS DIEGO STEVEN',
  '8191': 'FUENTES SALAZAR FELIPE GABRIEL',
  '8192': 'CORDONES SEVILLANO CARLOS ALFREDO',
  '8193': 'VERA IZURIETA NANCY CECILIA',
  '8194': 'ALAVA FIGUEROA KELVIN JEOVANNY',
  '8195': 'AVILES TAPIA ISRAEL',
  '8196': 'RAMIREZ BAIDAL WALTER FRANCISCO',
  '8197': 'SILVA URGILES JENNIFER STEFANIE',
  '8199': 'BUSTAMANTE HONORES JHON ORLANDO',
  '8200': 'RAMIREZ BENITEZ SERGIO DENIS',
  '8201': 'INTRIAGO HOLGUIN RUDDY ESTEFANIA',
  '8202': 'JIMENEZ CEDEÑO JAIRON JAVIER',
  '8203': 'LOOR GOMEZ GABRIELA MARIA',
  '8205': 'CASTILLO ARAUJO ANDREA ESTEFANIA',
  '8206': 'PORRAS JIMENEZ STALIN ROLANDO',
  '8207': 'MOLINA SANCHEZ FERNANDO GASTON',
  '8208': 'VARGAS BRAVO IVONNE LORENA',
  '8209': 'MONAR HOYOS JUAN GABRIEL',
  '8210': 'MARTINEZ CORNEJO DENNISS DIANELA',
  '8211': 'VASQUEZ VILLEGAS SONNIA CONCEPCION',
  '8212': 'BURGOS JIMENEZ ERWIN ERNESTO',
  '8213': 'ANCHUNDIA ELVIS ANGELO MACARIO',
  '8214': 'CUESTA VELIZ JOSE JAVIER',
  '8215': 'NARVAEZ CLERQUE WILLIAM ARMANDO',
  '8216': 'BRIONES PAREDES INGRID KATHERINE',
  '8217': 'HERRERA NOGUERA MICHAEL LEONEL',
  '8218': 'MURILLO RONQUILLO DELIA INES',
  '8219': 'SERRANO JAIME LILIANA DEL ROCIO',
  '8220': 'CASTRO MENDIETA KEYLA STEFANIA',
  '8221': 'DOMINGUEZ VALENCIA GABRIELA PATRICIA',
  '8222': 'CARRERA BELLO EDUARDO DAVID',
  '8223': 'INTRIAGO CASTILLO SILVANA LISSETTE',
  '8224': 'BRANQUE TOALA MARIA GUADALUPE',
  '8225': 'FLORENCIA MERA NADIA GERALDINE',
  '10731': 'ACOSTA ACOSTA KEVIN JEFERSON',
  '10732': 'GAROFALO MORA RONALDO ANDRES',
  '10733': 'GARCIA AYALA JAROD RENE',
  '10734': 'VILLACRES JARRO ISAAC TOMMY',
  '10735': 'MARQUEZ QUINTO SHARON ANDREINA',
  '10736': 'PADILLA DUCHI VICTORIA DEL CARMEN',
  '10737': 'YERBABUENA HUEBLA ANA SOFIA',
  '10738': 'VILLAMAR MONCADA MARLY NORALMA',
  '10739': 'ESTRADA TUALOMBO DIANA MARIANELA',
  '10740': 'CHANGO GUAITA SHAKIRA NATHALY',
  '10741': 'ELIZALDE TUTIVEN JUDITH YOLANDA',
  '10742': 'LOOR MOREIRA DENNISSE ARLETTE',
  '10743': 'BENAVIDES TORRES ISAAC SANDY',
  '10744': 'BENITES LITUMA LUIS GUSTAVO',
  '10745': 'QUITUISACA ROMERO MILENY FERNANDA',
  '10746': 'PARRA PALADINES DOMENICA NICOLE',
  '10747': 'RAMOS SOLANO KARLA GEOVANNA',
  '10748': 'CACUANGO MAJI MARTHA SUSANA',
  '10749': 'YUPANQUI FRANCO GENESIS LISBETH',
  '10750': 'ZAMBRANO ALVARADO TAYLY ELIZABETH',
  '10751': 'SALAS MOLINA JORGE JOSUE',
  '10752': 'MONAR HOYOS GABRIEL ALEJANDRO',
  '10753': 'ESPIN TORRES ALFONSO RUBEN',
  '10754': 'GONZALEZ VELOZ BRYAN JORDY',
  '10755': 'MOREIRA GILCES GISELLA KATHERINE',
  '10756': 'FLORES VELOZ ANTHONY JOEL',
  '10757': 'PLAZA GUERRERO ANGELO GREGORIO',
  '10758': 'ALARCON OLEA BYRON VICENTE',
  '10759': 'GOMEZ MOLINA JEAN PIERRE',
  '10760': 'PEÑAFIEL NAULA BRYAN ORLANDO',
  '10761': 'ALARCON CHAVEZ GREGORIO ALFREDO',
  '10762': 'GOMEZ BUENAÑO JULIO ALEXANDER',
  '10763': 'SALINAS ZAMBRANO YESLY YAMILET',
  '10764': 'MEJIA LAMILLA MELANIE LILIBETH',
  '10765': 'SANCHEZ ROSALES REBECA ELIZABETH',
  '10766': 'AYALA LOZANO LUIS DAVID',
  '10767': 'GUERRERO MOSQUERA LISBETH ODALIS',
  '10768': 'ZULETA VILLEGAS DANIELA CECILIA',
  '10769': 'CADENA CADENA GABRIEL ALEXANDER',
  '10770': 'BENAVIDES TORRES SEBASTIAN SAUL',
  '10771': 'BOADA RODRIGUEZ NAGELY NICOLE',
  '10772': 'MONCAYO GUAIRACAJA VERONICA ALEXANDRA',
  '10773': 'MIÑO RENGIFFO DIEGO NEPTALI',
  '10774': 'RUIZ GARCIA DAYHANNA NARCISA',
  '10775': 'MORAN ESTRELLA ANNY ANDREA',
  '10776': 'SALCEDO ARCENTALES IDA EDILMA',
  '10777': 'MOREIRA JARA ANGELI NAOMI',
  '10778': 'VACA FIGUEROA GENESIS ZARYA',
  '10779': 'PEREZ CEVALLOS PAOLA LISSETH',
  '10780': 'GARCIA CORDOVA RENE JOAQUIN',
  '10781': 'SALAVARRIA QUINTANA AILEN NICOLE',
  '10782': 'ALCIVAR ANDRADE GARY JESUS',
  '10783': 'ROBALINO FLORES ELIANA ALEJANDRA',
  '10784': 'PEREZ PARRAGA ROGER STEVEN',
  '10785': 'CRESPIN CRESPIN JAIRO DARIO',
  '10786': 'COLOMA PARDO ALISSON MISHELL',
  '10787': 'ESTEVEZ PINO ANGEL BRYAN',
  '10788': 'PINTO SESME LEONELA GEOMAIRA',
  '10789': 'PILAY MORAN SILVIA LISSETTE',
  '10790': 'MARIN ALBAN STEFANY LISBETH',
  '10791': 'ARREAGA NARVAEZ SOLANGE BRIGGITTE',
  '10792': 'NIETO CHIRIGUAYA STANLEY RUDNEY',
  '10793': 'VILLA VINUEZA FABRICIO JOSE',
  '10794': 'PARCO CHANGO ANTONY JHOEL',
  '10795': 'VILELA CEVALLOS MARIA JOSE',
  '10796': 'ANCHUNDIA HENRIQUEZ JONATHAN ALEXIS',
  '10797': 'ALMACHE UNAPUCHA MARLON STEVEN',
  '10798': 'SARANGO GUALAN JOSE MANUEL',
  '10799': 'ESPIN ORTEGA JOEL EDUARDO',
  '10800': 'FERNANDEZ QUIÑONEZ GENESIS IBETH',
  '10801': 'MITE VILLACRES SANDY PATRICIA',
  '10802': 'VILLEGAS MOSQUERA ORLYN MICHAEL',
  '10803': 'SANGA HERNANDEZ PRISCILLA LILIBETH',
  '10804': 'VARGAS LAPO HECTOR JEFFERSON',
  '10805': 'ZHUNIO MERCHAN KEVIN MAURICIO',
  '10806': 'LOMBEIDA QUINTANA JHONY ALEXANDER',
  '10807': 'ANCHUNDIA INTRIAGO KENNIA JOHANNA',
  '10808': 'QUIÑONEZ NAZARENO CINDY JOHANNA',
  '10809': 'SUAREZ BARZOLA CRISTINA FERNANDA',
  '10810': 'BARCIA MENDOZA FRANCISCO JAVIER',
  '10811': 'ARMIJO TRIANA ROGGER LENIN',
  '10812': 'GUAMBO GAMARRA JHON JOSUE',
  '10813': 'LOPEZ VALDIVIEZO CYNTHIA MARIA',
  '10814': 'RENTERIA VARGAS SASHA ANAHI',
  '10815': 'PEÑA CASTRO ANTHONY RICARDO',
  '10816': 'NAVIA MOREIRA XIOMARA ESTEFANIA',
  '10817': 'PEÑAFIEL GORDON DAVID ALEXANDER',
  '10818': 'DUME GOMEZ AXEL ELADIO',
  '10819': 'MOREIRA MOGRO MELANYE MICHELLE',
  '10820': 'ORTEGA BONILLA KATERIN GABRIELA',
  '10821': 'RODRIGUEZ CEDENO HECTOR ISRAEL',
  '10822': 'VASQUEZ PENAFIEL BRYAN ANTHONY',
  '10823': 'MONTESDEOCA JUNQUI CAROLINA STEPHANIA',
  '10824': 'SORIANO CHAGUAY ALFREDO LEONARDO',
  '10825': 'FREIRE CHAVEZ BRYAN ALONSO',
  '10826': 'CORONEL VERA KATHERYN ISABEL',
  '10827': 'ALDAZ SILVA ANTHONY VLADIMIR',
  '10828': 'CORDONES SEVILLANO ELIAS DAVID',
  '10829': 'SUAREZ TOMALA ANDY JAVIER',
  '10830': 'SUCO SANTISTEVAN MERCEDES NARCISA',
  '10831': 'HERRERA ALVARADO WASHINGTON STEEVEN',
  '10832': 'LINO PEÑA KEVIN EDUARDO',
  '10833': 'MAGALLANES PACHAY ROMARIO ALEXANDER',
  '10834': 'CABRERA POZO MARIUXI LISSETTE',
  '10835': 'AREVALO ERAZO JOSE ANDRES',
  '10836': 'QUINCHUELA CAMACHO WUILMAN SANTIAGO',
  '10837': 'RODRIGUEZ VALVERDE PATRICK JOHNSON',
  '10839': 'NIEBLA DELGADO MARLON JONATHAN',
  '10840': 'TIGRE ROJAS DAYANA MELINA',
  '10841': 'CORONEL MUÑIZ ERICK IVAN',
  '10842': 'PIGUAVE LOPEZ JOSELYN AURORA',
  '10843': 'FIERRO CASTILLO JOSUEPH SEBASTIAN',
  '10844': 'CASTAÑEDA NARVAEZ CHRISTOPHER ALEJANDRO',
  '10845': 'JARA FERNANDEZ LISBETH KATHERINE',
  '10846': 'MARTINEZ VACA MARIO STALIN',
  '10847': 'ORELLANA PESANTEZ JOSELYN PAULETTE',
  '10848': 'ARTEAGA ZAMBRANO NOELIA MISHELLE',
  '10849': 'CAIZA ROJAS BRITNEY ELIZABETH',
  '10850': 'ANZULES PLUAS ANGEL JESUS',
  '10851': 'SANCHEZ HOLGUIN DENISSE TAMARA',
  '10852': 'QUITO RODRIGUEZ XIOMARA SOFIA',
  '10853': 'GUAPI AVEMANAY CARLOS ALEXIS',
  '10854': 'GONZALEZ ACOSTA GINGER SCARLETT',
  '10855': 'PORRAS URGILES YEISON LEONNEL',
  '10856': 'TORRES SANCHEZ STANLEY LENIN',
  '10857': 'AVILES MACHARE CARLOS MANUEL',
  '10858': 'MORAN PALACIOS ELIAN ALEXANDER',
  '10859': 'SERDAN DAVALOS KEVIN DARIO',
  '10860': 'WONG HERNANDEZ KEIKO SOFIA',
  '10861': 'VERGARA FUENTES YELIN PAULINA',
  '10862': 'PEÑAFIEL VILLEGAS GEORGE HARRY',
  '10863': 'RAMOS ZHUNIO GILSON OSWALDO',
  '10864': 'JIMENEZ SARMIENTO RONNY BRANNIMIR',
  '10865': 'BRAVO ZAMBRANO ANDY SANTIAGO',
  '10866': 'HUEBLA TAYUPANDA NAYDA JOHANNA',
  '10867': 'ECHEVERRIA MATUTE MELVIS HERNAN',
  '10868': 'ALBAN CUESTAS OSCAR MARTIN',
  '10869': 'MAURAD CARRION BOLIVAR ADRIAN',
  '10870': 'SINCHIGUANO VILLAMAR VICTOR ALEJANDRO',
  '10871': 'TAMA ALTAMIRANO MADELINE VANESSA',
  '10872': 'GUIRACOCHA BARRERA RICARDO JAVIER',
  '10873': 'RUIZ MURILLO MANUEL ARIEL',
  '10874': 'HUEBLA TAYUPANDA LUIS GUSTAVO',
  '10875': 'CHAVEZ GARCIA JONATHAN ANTONIO',
  '10876': 'SANTANA SUAREZ RONNY ALEJANDRO',
  '10877': 'SALAZAR ZAMBRANO JULIO ENRIQUE',
  '10878': 'PEÑAHERRERA CHIPRE TANIA IZAMARA',
  '10879': 'PIZA NAVAS ANTONIO XAVIER',
  '10880': 'CAMPUZANO ARRIAGA KENNETH JOSUE',
  '10881': 'AGUILAR NARANJO EDINSON ALEXANDER',
  '10882': 'LEON MACIAS MIGUEL ATHILA',
  '10883': 'CHIMBO SANTILLAN LINDA MICHELLE',
  '10884': 'CUESTA DELGADO JOEL ALEXANDER',
  '10885': 'MACIAS CHASIN ODALYS PIERINA',
  '10886': 'SAQUICELA REMACHE MARCELO ENRIQUE',
  '10887': 'MORA RAMOS JESUS RONNY',
  '10888': 'ROGGIERO PAREDES FERNANDO JAVIER',
  '10889': 'GAVILANES PINTO MARIA GABRIELA',
  '10890': 'ACOSTA CHACON ANTHONY ENRIQUE',
  '10891': 'IBARRA VALENCIA BRUCE STIVEEN',
  '10892': 'BUNGACHO MENDEZ JORGE ISIDRO',
  '10893': 'NAVARRETE ALAVA JORDY HERNAN',
  '10894': 'NUÑEZ MONTOYA LUIS FELIPE',
  '10895': 'ALVAREZ RUIZ JORGE LUIS',
  '10896': 'CONSTANTE CARDENAS ERICK ALEJANDRO',
  '10897': 'PEÑAFIEL NAREA RONNY STEVEN',
  '10898': 'PALMA CARDOZO CHRISTIAN VICENTE',
  '10899': 'ALVAREZ GRANJA WILLIAM EDUARDO',
  '10900': 'MARURI RODRIGUEZ HAROLD RENE',
  '10901': 'VILELA NAVARRETE KENY ANDRES',
  '10902': 'MERINO MALDONADO VICTOE EDUARDO',
  '10903': 'PAZMIÑO TINAJERO EDGAR SEBASTIAN',
  '10904': 'DE LA CRUZ PARRAGA JOHN ALEXANDER',
  '10905': 'MINAYA ALVARADO WILLIAM JAHIR',
  '10906': 'BRAVO BASTIDAS FERNANDO ZACARIAS',
  '10907': 'ALTAMIRANO MOYA MARIO MIGUEL',
  '10908': 'MORALES GUAMAN BRYAN ADRIAN',
  '10909': 'TORRES ACOSTA ALEJANDRO JOSE',
  '10910': 'APOLINARIO MORENO WILLIAN EVANDER',
  '10911': 'RUGEL RUGEL JOSUE RAFAEL',
  '10912': 'BARRERA MERCHAN JAMILET ANDREINA',
  '10913': 'PILATAXI VALLA OSMAR NELSON',
  '10914': 'MORETA LLIVIPUMA JONATHAN DAVID',
  '10915': 'ROGGIERO PAREDES JAVIER FERNANDO',
  '6199':  'ASTUDILLO LAGE IVAN GEOVANNY',
  
};

// ==================== AUTOCOMPLETADO POR CÓDIGO INSTITUCIONAL ====================
async function autocompletarNombre(codigo) {
  const el = document.getElementById('nombre-autocompletado');
  if (!el) return;
  const cod = (codigo || '').trim();
  if (cod.length < 2) { el.textContent = ''; el.className = ''; return; }

  // Buscar primero en catálogo local
  const nombre = CODIGOS_PERSONAL[cod];
  if (nombre) {
    el.textContent = '✅ ' + nombre;
    el.className = 'autocomplete-ok';
    return;
  }

  // Si no está en local, buscar en Firestore (catálogo cargado)
  const catalogoFS = await cargarCatalogoFS();
  const nombreFS = catalogoFS[cod];
  if (nombreFS) {
    el.textContent = '✅ ' + nombreFS;
    el.className = 'autocomplete-ok';
  } else {
    el.textContent = '⚠️ CÓDIGO NO ENCONTRADO EN EL REGISTRO';
    el.className = 'autocomplete-warn';
  }
}

let _catalogoFSCache = null;
async function cargarCatalogoFS() {
  if (_catalogoFSCache) return _catalogoFSCache;
  try {
    const doc = await db.collection('codigos_personal').doc('catalogo').get();
    _catalogoFSCache = doc.exists ? doc.data().codigos || {} : {};
  } catch(e) {
    _catalogoFSCache = {};
  }
  return _catalogoFSCache;
}

function getNombrePorCodigo(codigo) {
  const cod = (codigo || '').trim();
  return CODIGOS_PERSONAL[cod] || (_catalogoFSCache && _catalogoFSCache[cod]) || null;
}

// ==================== CONFIGURACIÓN INICIAL ====================
const GOOGLE_CLIENT_ID = '571154981190-e83q5clu440b0p8jqikrqkq3r6v2qrdt.apps.googleusercontent.com';

// ==================== TOASTS ====================
function showToast(msg, type='info', duration=3500){
  const icons = {success:'✅', error:'❌', info:'ℹ️'};
  const container = document.getElementById('toast-container');
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  toast.innerHTML = `<span>${icons[type]||'•'}</span><span>${msg}</span>`;
  container.appendChild(toast);
  setTimeout(()=>{
    toast.classList.add('toast-out');
    toast.addEventListener('animationend',()=>toast.remove());
  }, duration);
}

// ==================== LOGIN TABS ====================
function switchLoginTab(tab){
  document.querySelectorAll('.login-tab-btn').forEach(b=>b.classList.remove('active'));
  document.querySelectorAll('.login-panel').forEach(p=>p.classList.remove('active'));
  document.getElementById('panel-'+tab).classList.add('active');
  [...document.querySelectorAll('.login-tab-btn')].find(b=>b.textContent.toLowerCase().includes(tab==='ingresar'?'ingresar':'registr')).classList.add('active');
}

// ==================== LOGIN CON USUARIO/CONTRASEÑA ====================
async function doLoginPass(){
  const user = document.getElementById('login-user').value.trim();
  const pass = document.getElementById('login-pass').value;
  if(!user||!pass){ mostrarError('INGRESA USUARIO Y CONTRASEÑA'); return; }
  const found = USERS.find(u=>u.user===user);
  if(!found){ mostrarError('USUARIO NO ENCONTRADO'); addLog(user,'DESCONOCIDO','fail'); return; }
  if(isBlocked(found)){ mostrarError('CUENTA BLOQUEADA. CONTACTE AL ADMINISTRADOR.'); addLog(user,found.nombre,'fail'); return; }
  const hashed = await hashPass(pass);
  if(hashed !== found.passHash){ mostrarError('CONTRASEÑA INCORRECTA'); addLog(user,found.nombre,'fail'); return; }
  addLog(found.user,found.nombre,'ok',found.email||'');
  entrarAlSistema(found, null);
}

// Usuarios por defecto (solo admin)
const DEFAULT_USERS = [
  { user:'admin', passHash:'', nombre:'ADMINISTRADOR SISTEMA', rol:'admin', email:'ctepersonal0@gmail.com', blocked: false, area:'', provincia:'', codigo:'' },
];

const FILES_BASE = [
  { id:1779224557782, nombre:'HISTORIAL CTE', seccion:'organico', tipo:'excel', desc:'', fecha:'19/05/2026', urlOriginal:'https://drive.google.com/drive/folders/1IKszLxBRMZTpv0CyJYaFJ11KbmaftAlW?usp=sharing' },
];

// ==================== FUNCIONES DE HASH ====================
async function hashPass(pass) {
  const encoder = new TextEncoder();
  const data = encoder.encode(pass);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// ==================== FIRESTORE CONFIGURACIÓN ====================
let USERS = [];
let solicitudesUnsubscribe = null;

async function initializeUsers() {
  showToast('Conectando a la nube...', 'info', 2000);
  db.collection('users').onSnapshot(async (snapshot) => {
    const usersFromFirestore = [];
    snapshot.forEach(doc => { usersFromFirestore.push({ id: doc.id, ...doc.data() }); });
    if (usersFromFirestore.length > 0) {
      USERS = usersFromFirestore;
      localStorage.setItem('cte_users_cache', JSON.stringify(USERS));
      let needsSave = false;
      for (let u of USERS) {
        if (!u.passHash) {
          const defaultPass = u.user === 'admin' ? '@dmin2026' : 'cte2026';
          u.passHash = await hashPass(defaultPass);
          needsSave = true;
        }
      }
      if (needsSave) await saveUsers();
      if (currentUser && currentUser.rol === 'admin') renderAdmin();
      if (currentUser) document.getElementById('stat-total').textContent = USERS.length;
    } else if (USERS.length === 0) {
      USERS = JSON.parse(JSON.stringify(DEFAULT_USERS));
      for (let u of USERS) {
        if (!u.passHash) {
          const defaultPass = u.user === 'admin' ? '@dmin2026' : 'cte2026';
          u.passHash = await hashPass(defaultPass);
        }
      }
      await saveUsers();
    }
  }, (error) => {
    console.error('Error escuchando usuarios:', error);
    const cache = localStorage.getItem('cte_users_cache');
    if (cache) USERS = JSON.parse(cache);
    else USERS = JSON.parse(JSON.stringify(DEFAULT_USERS));
  });
}

async function saveUsers() {
  for (let user of USERS) {
    const userData = { ...user };
    delete userData.id;
    await db.collection('users').doc(user.user).set(userData, { merge: true });
  }
  localStorage.setItem('cte_users_cache', JSON.stringify(USERS));
}

function getUserByEmail(email) {
  return USERS.find(u => u.email && u.email.toLowerCase() === email.toLowerCase());
}

function isBlocked(userObj) { return userObj.blocked === true; }

function toggleBlockUser(username, block) {
  const user = USERS.find(u => u.user === username);
  if (!user || user.rol === 'admin') return;
  user.blocked = block;
  saveUsers();
  if (currentUser && currentUser.rol === 'admin') renderAdmin();
}

async function deleteUser(username) {
  const user = USERS.find(u => u.user === username);
  if (!user) return;
  if (user.rol === 'admin') { showToast('NO SE PUEDE ELIMINAR AL ADMINISTRADOR PRINCIPAL', 'error'); return; }
  openModal('ELIMINAR USUARIO', `¿ELIMINAR A ${user.nombre}?`, async () => {
    USERS = USERS.filter(u => u.user !== username);
    await db.collection('users').doc(username).delete();
    localStorage.setItem('cte_users_cache', JSON.stringify(USERS));
    renderAdmin();
    showToast(`USUARIO ${user.nombre} ELIMINADO`, 'success');
  });
}

async function toggleAdminRole(username) {
  const user = USERS.find(u => u.user === username);
  if (!user || user.user === currentUser.user) { showToast('NO PUEDES MODIFICAR TU PROPIO ROL', 'error'); return; }
  const nuevoRol = user.rol === 'admin' ? 'user' : 'admin';
  const label = nuevoRol === 'admin' ? 'ADMINISTRADOR' : 'USUARIO';
  openModal('CAMBIAR ROL', `¿CAMBIAR ROL DE ${user.nombre} A ${label}?`, async () => {
    user.rol = nuevoRol;
    await saveUsers();
    renderAdmin();
    showToast(`ROL DE ${user.nombre} CAMBIADO A ${label}`, 'success');
  });
}

// ==================== SOLICITUDES DE REGISTRO ====================
function listenToSolicitudes() {
  if (solicitudesUnsubscribe) solicitudesUnsubscribe();
  solicitudesUnsubscribe = db.collection('solicitudes')
    .where('estado', '==', 'pendiente')
    .onSnapshot((snapshot) => {
      const solicitudes = [];
      snapshot.forEach(doc => { solicitudes.push({ id: doc.id, ...doc.data() }); });
      solicitudes.sort((a, b) => {
        const ta = a.timestamp ? a.timestamp.seconds : 0;
        const tb = b.timestamp ? b.timestamp.seconds : 0;
        return tb - ta;
      });
      window._solicitudesCache = solicitudes;
      if (currentUser && currentUser.rol === 'admin') {
        renderSolicitudes();
        if (solicitudes.length > 0) {
          showToast(`📨 ${solicitudes.length} solicitud(es) pendiente(s) de aprobación`, 'info', 5000);
          try {
            const audio = new Audio('https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3');
            audio.volume = 0.3;
            audio.play().catch(e => console.log('Audio no soportado'));
          } catch(e) {}
        }
      }
    }, (error) => { console.error('Error escuchando solicitudes:', error); });
}

// ==================== SOLICITAR REGISTRO (con validación de código) ====================
async function solicitarRegistro() {
  const area     = document.getElementById('reg-area').value.trim().toUpperCase();
  const provincia= document.getElementById('reg-provincia').value.trim().toUpperCase();
  const codigo   = document.getElementById('reg-codigo').value.trim();
  const email    = document.getElementById('reg-email').value.trim().toLowerCase();

  if (!area || !provincia || !codigo || !email) {
    mostrarError('COMPLETA TODOS LOS CAMPOS');
    return;
  }

  // ── VALIDACIÓN DE CÓDIGO INSTITUCIONAL ──
  const nombreOficial = getNombrePorCodigo(codigo);
  if (!nombreOficial) {
    mostrarError('⚠️ CÓDIGO INSTITUCIONAL NO VÁLIDO. VERIFICA TU NÚMERO DE CÓDIGO EN EL REGISTRO DE PERSONAL.');
    const el = document.getElementById('nombre-autocompletado');
    if (el) { el.textContent = '❌ CÓDIGO NO REGISTRADO'; el.className = 'autocomplete-error'; }
    return;
  }

  if (!email.endsWith('@gmail.com')) {
    mostrarError('SOLO SE PERMITEN CORREOS DE GMAIL');
    return;
  }

  const usuarioExistente = getUserByEmail(email);
  if (usuarioExistente) {
    const nombre = usuarioExistente.nombre || email;
    mostrarError(`⚠️ EL CORREO ${email.toUpperCase()} YA ESTÁ REGISTRADO COMO "${nombre}". INICIA SESIÓN CON GOOGLE O CONTACTA AL ADMINISTRADOR.`);
    const googleWrap = document.getElementById('google-btn-wrap');
    if (googleWrap) {
      googleWrap.style.outline = '2px solid #e67e22';
      googleWrap.style.borderRadius = '6px';
      setTimeout(() => { googleWrap.style.outline = ''; googleWrap.style.borderRadius = ''; }, 5000);
    }
    return;
  }

  const aprobadaSnap = await db.collection('solicitudes').where('email', '==', email).where('estado', '==', 'aprobada').get();
  if (!aprobadaSnap.empty) {
    mostrarError(`✅ TU SOLICITUD YA FUE APROBADA. INICIA SESIÓN CON GOOGLE USANDO ${email.toUpperCase()}.`);
    return;
  }

  const existingSolicitud = await db.collection('solicitudes').where('email', '==', email).where('estado', '==', 'pendiente').get();
  if (!existingSolicitud.empty) {
    mostrarError('YA TIENES UNA SOLICITUD PENDIENTE. ESPERA LA APROBACIÓN DEL ADMINISTRADOR.');
    return;
  }

  showToast('ENVIANDO SOLICITUD...', 'info', 2500);

  const nuevaSolicitud = {
    area,
    provincia,
    codigo,
    nombreOficial,   // ← guardamos el nombre oficial del catálogo
    email,
    fecha: new Date().toLocaleDateString('es-EC'),
    timestamp: firebase.firestore.FieldValue.serverTimestamp(),
    estado: 'pendiente'
  };

  await db.collection('solicitudes').add(nuevaSolicitud);

  mostrarExito(`✅ SOLICITUD ENVIADA. NOMBRE REGISTRADO: ${nombreOficial}. ESPERA LA APROBACIÓN DEL ADMINISTRADOR.`);
  document.getElementById('reg-area').value = '';
  document.getElementById('reg-provincia').value = '';
  document.getElementById('reg-codigo').value = '';
  document.getElementById('reg-email').value = '';
  const el = document.getElementById('nombre-autocompletado');
  if (el) { el.textContent = ''; el.className = ''; }
}

async function aprobarSolicitud(id) {
  const docRef = db.collection('solicitudes').doc(id);
  const doc = await docRef.get();
  if (!doc.exists) return;
  const solicitud = doc.data();

  // Usar nombreOficial si existe, si no construir desde campos
  const nombreCompleto = solicitud.nombreOficial ||
    `${solicitud.area} - ${solicitud.provincia} (${solicitud.codigo})`;

  const baseUsername = solicitud.email.split('@')[0];
  let username = baseUsername;
  let counter = 1;
  while (USERS.find(u => u.user === username)) {
    username = `${baseUsername}${counter}`;
    counter++;
  }

  const nuevoUsuario = {
    user: username,
    passHash: '',
    nombre: nombreCompleto,
    rol: 'user',
    email: solicitud.email,
    blocked: false,
    area: solicitud.area,
    provincia: solicitud.provincia,
    codigo: solicitud.codigo,
    nombreOficial: solicitud.nombreOficial || '',
    creado: firebase.firestore.FieldValue.serverTimestamp()
  };

  USERS.push(nuevoUsuario);
  await saveUsers();
  await docRef.update({ estado: 'aprobada', fechaAprobacion: firebase.firestore.FieldValue.serverTimestamp() });

  addLog(username, nombreCompleto, 'aprobacion', solicitud.email,
    `CUENTA APROBADA POR ADMINISTRADOR - ÁREA: ${solicitud.area}, PROVINCIA: ${solicitud.provincia}, CÓDIGO: ${solicitud.codigo}, NOMBRE: ${nombreCompleto}`);

  if (currentUser && currentUser.rol === 'admin') renderAdmin();
  showToast(`✅ USUARIO ${nombreCompleto} APROBADO CORRECTAMENTE.`, 'success');
}

async function rechazarSolicitud(id) {
  const docRef = db.collection('solicitudes').doc(id);
  const doc = await docRef.get();
  const solicitud = doc.data();
  openModal('RECHAZAR SOLICITUD', `¿RECHAZAR LA SOLICITUD DE ${solicitud.area} - ${solicitud.provincia} (${solicitud.codigo})?`, async () => {
    await docRef.update({ estado: 'rechazada', fechaRechazo: firebase.firestore.FieldValue.serverTimestamp() });
    if (currentUser && currentUser.rol === 'admin') renderAdmin();
    showToast('❌ Solicitud rechazada', 'error');
  });
}

async function renderSolicitudes() {
  const container = document.getElementById('solicitudes-list');
  if (!container) return;
  container.innerHTML = '<div class="file-empty">⏳ CARGANDO SOLICITUDES...</div>';
  const snapshot = await db.collection('solicitudes').where('estado', '==', 'pendiente').get();
  const solicitudes = [];
  snapshot.forEach(doc => { solicitudes.push({ id: doc.id, ...doc.data() }); });
  solicitudes.sort((a, b) => {
    const ta = a.timestamp ? a.timestamp.seconds : 0;
    const tb = b.timestamp ? b.timestamp.seconds : 0;
    return tb - ta;
  });
  if (solicitudes.length === 0) {
    container.innerHTML = '<div class="file-empty">📭 NO HAY SOLICITUDES PENDIENTES</div>';
    return;
  }
  container.innerHTML = `
    <div class="files-grid">
      ${solicitudes.map(s => {
        const nombreDisplay = s.nombreOficial
          ? `<br><span style="color:#1a7a4a;font-weight:600">👤 ${esc(s.nombreOficial)}</span>`
          : '';
        return `
        <div class="file-card">
          <div class="file-card-top">
            <div class="file-type-icon file-type-other">📧</div>
            <div>
              <div class="file-card-name">${esc(s.area)}</div>
              <div class="file-card-meta">
                PROVINCIA: ${esc(s.provincia)}<br>
                CÓDIGO: ${esc(s.codigo)}${nombreDisplay}<br>
                CORREO: ${esc(s.email)}<br>
                SOLICITADO: ${s.fecha}
              </div>
            </div>
          </div>
          <div class="file-card-actions">
            <button class="file-card-btn file-card-btn-open btn-approve" onclick="aprobarSolicitud('${s.id}')">✓ APROBAR</button>
            <button class="file-card-btn file-card-btn-del btn-reject" onclick="rechazarSolicitud('${s.id}')">✗ RECHAZAR</button>
          </div>
        </div>`;
      }).join('')}
    </div>`;
}

// ==================== BITÁCORA EN FIRESTORE ====================
async function addLog(usuario, nombre, estado, email='', details=''){
  const now = new Date();
  const dev = /Mobi|Android/i.test(navigator.userAgent) ? 'MÓVIL' : 'COMPUTADORA';
  const logEntry = {
    usuario, nombre, estado, email, details,
    fecha: now.toLocaleDateString('es-EC'),
    hora: now.toLocaleTimeString('es-EC'),
    device: dev,
    timestamp: firebase.firestore.FieldValue.serverTimestamp()
  };
  await db.collection('logs').add(logEntry);
}

async function getLogs() {
  const snapshot = await db.collection('logs').orderBy('timestamp', 'desc').limit(500).get();
  const logs = [];
  snapshot.forEach(doc => { logs.push(doc.data()); });
  return logs;
}

// ==================== EXPORTAR A EXCEL ====================
function exportUsersToExcel() {
  let csv = "NOMBRE,USUARIO,ROL,EMAIL,ÁREA,PROVINCIA,CÓDIGO INSTITUCIONAL,NOMBRE OFICIAL,ESTADO\n";
  USERS.forEach(u => {
    csv += `"${u.nombre}","${u.user}","${u.rol === 'admin' ? 'ADMINISTRADOR' : 'USUARIO'}","${u.email || ''}","${u.area || ''}","${u.provincia || ''}","${u.codigo || ''}","${u.nombreOficial || ''}","${u.blocked ? 'BLOQUEADO' : 'ACTIVO'}"\n`;
  });
  downloadCSV(csv, `usuarios_cte_${new Date().toISOString().slice(0,19)}.csv`);
}

async function exportLogsToExcel() {
  const logs = await getLogs();
  let csv = "USUARIO,NOMBRE,EMAIL,FECHA,HORA,DISPOSITIVO,ESTADO,DETALLES\n";
  logs.forEach(l => {
    let estadoTexto = l.estado === 'ok' ? 'INGRESO EXITOSO' : (l.estado === 'aprobacion' ? 'APROBACIÓN DE CUENTA' : 'INTENTO FALLIDO');
    csv += `"${l.usuario}","${l.nombre}","${l.email || ''}","${l.fecha}","${l.hora}","${l.device}","${estadoTexto}","${l.details || ''}"\n`;
  });
  downloadCSV(csv, `bitacora_cte_${new Date().toISOString().slice(0,19)}.csv`);
}

function downloadCSV(csv, filename) {
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ==================== ARCHIVOS ====================
function getFiles(){
  try{
    const local = JSON.parse(localStorage.getItem('cte_files')||'[]');
    const localIds = new Set(local.map(f=>f.id));
    const base = FILES_BASE.filter(f=>!localIds.has(f.id));
    return [...base, ...local];
  }catch(e){ return [...FILES_BASE]; }
}
function saveFiles(f){
  const baseIds = new Set(FILES_BASE.map(x=>x.id));
  localStorage.setItem('cte_files', JSON.stringify(f.filter(x=>!baseIds.has(x.id))));
}

function extractDriveId(url){
  const m1 = url.match(/\/d\/([a-zA-Z0-9_-]{15,})/);
  const m2 = url.match(/[?&]id=([a-zA-Z0-9_-]{15,})/);
  if(m1) return m1[1];
  if(m2) return m2[1];
  return null;
}
function driveViewUrl(url, tipo){
  const id = extractDriveId(url);
  if(!id) return url;
  if(tipo === 'pdf' || tipo === 'img') return 'https://drive.google.com/file/d/' + id + '/view?usp=sharing';
  return 'https://docs.google.com/viewer?url=' + encodeURIComponent('https://drive.google.com/uc?id=' + id);
}
function driveDownloadUrl(url){
  const id = extractDriveId(url);
  if(!id) return url;
  return 'https://drive.google.com/uc?export=download&id=' + id;
}
function verifyDriveLink(url){
  const id = extractDriveId(url);
  if(id) showToast(`ID DE DRIVE DETECTADO: ${id} — ARCHIVO ACCESIBLE`, 'success');
  else showToast('NO SE PUDO EXTRAER EL ID. USA UN ENLACE ESTÁNDAR DE DRIVE.', 'error');
}

// ==================== SESIÓN Y UI ====================
let currentUser = null;
let inactivityTimer;

function resetInactivityTimer() {
  clearTimeout(inactivityTimer);
  inactivityTimer = setTimeout(() => { if (currentUser) doLogout(); }, 30 * 60 * 1000);
}
document.body.addEventListener('click', resetInactivityTimer);
document.body.addEventListener('keypress', resetInactivityTimer);

function entrarAlSistema(found, foto){
  currentUser = found;
  document.getElementById('screen-login').style.display = 'none';
  document.getElementById('screen-main').style.display  = 'block';
  document.getElementById('display-user').textContent = found.nombre + ' (' + found.user + ')';
  const rb = document.getElementById('display-role-badge');
  rb.textContent = found.rol === 'admin' ? 'ADMIN' : 'USUARIO';
  rb.className = 'badge ' + (found.rol==='admin' ? 'badge-admin' : 'badge-user');
  const isAdmin = found.rol === 'admin';
  document.getElementById('nav-admin').style.display = isAdmin ? 'block' : 'none';
  document.getElementById('print-btn').style.display = isAdmin ? 'block' : 'none';
  renderDashboard();
  renderAllSectionFiles();
  if (isAdmin) renderAdmin();
  resetInactivityTimer();
  showToast(`BIENVENIDO, ${found.nombre.split(' ')[0]}`, 'success', 3000);
}

function initGoogle(){
  if(typeof google === 'undefined') { setTimeout(initGoogle, 300); return; }
  google.accounts.id.initialize({ client_id: GOOGLE_CLIENT_ID, callback: onGoogleToken, ux_mode: 'popup' });
  const wrap = document.getElementById('google-btn-wrap');
  if(wrap){
    google.accounts.id.renderButton(wrap, { theme:'outline', size:'large', width: 320, text:'signin_with', shape:'rectangular', logo_alignment:'left' });
    document.getElementById('btn-google-fallback').style.display = 'none';
  }
}
window.addEventListener('load', initGoogle);

function loginConGoogle(){
  if(typeof google === 'undefined'){ mostrarError('CARGANDO GOOGLE, INTENTA EN UN MOMENTO.'); return; }
  google.accounts.id.prompt(notification => {
    if(notification.isNotDisplayed() || notification.isSkippedMoment()){
      const btn = document.querySelector('#google-btn-wrap div[role=button]');
      if(btn) btn.click();
    }
  });
}

function onGoogleToken(response){
  try{
    const payload = JSON.parse(atob(response.credential.split('.')[1]));
    const email = payload.email.toLowerCase();
    const user = getUserByEmail(email);
    if (!user) {
      mostrarError('❌ NO TIENES UNA CUENTA APROBADA. SOLICITA REGISTRO PRIMERO Y ESPERA LA APROBACIÓN DEL ADMINISTRADOR.');
      return;
    }
    if(user.blocked){ mostrarError('CUENTA BLOQUEADA. CONTACTE AL ADMINISTRADOR.'); addLog(user.user, user.nombre, 'fail', email); return; }
    addLog(user.user, user.nombre, 'ok', email);
    entrarAlSistema(user, payload.picture);
  }catch(e){ console.error(e); mostrarError('ERROR AL PROCESAR LA RESPUESTA DE GOOGLE.'); }
}

function doLogout(){
  currentUser = null;
  document.getElementById('screen-main').style.display = 'none';
  document.getElementById('screen-login').style.display = 'flex';
  document.getElementById('nav-admin').style.display = 'none';
  document.getElementById('print-btn').style.display = 'none';
}

// ==================== RENDERIZADO PRINCIPAL ====================
async function renderDashboard(){
  const logs = await getLogs();
  const hoy = new Date().toLocaleDateString('es-EC');
  const hoyOk = logs.filter(l=>l.fecha===hoy && l.estado==='ok').length;
  const hoyFail = logs.filter(l=>l.fecha===hoy && l.estado==='fail').length;
  const last = logs.filter(l=>l.estado==='ok')[0];
  document.getElementById('stat-total').textContent = USERS.length;
  document.getElementById('stat-hoy').textContent = hoyOk;
  document.getElementById('stat-fail').textContent = hoyFail;
  if(last){ document.getElementById('stat-last').textContent = last.nombre.split(' ')[0]; document.getElementById('stat-last-time').textContent = last.fecha+' '+last.hora; }
  const isAdmin = currentUser && currentUser.rol === 'admin';
  const statsWrap = document.getElementById('dashboard-stats');
  if (statsWrap) statsWrap.style.display = isAdmin ? '' : 'none';
  document.getElementById('dashboard-bitacora').style.display = isAdmin ? 'block' : 'none';
  document.getElementById('dashboard-no-admin').style.display = isAdmin ? 'none' : 'block';
  if(isAdmin){
    const recent = [...logs].slice(0,15);
    document.getElementById('log-count-label').textContent = logs.length+' REGISTROS';
    document.getElementById('log-tbody').innerHTML = recent.map(l=>`<tr><td>${esc(l.usuario)}</td><td>${esc(l.nombre)}</td><td>${l.fecha} ${l.hora}</td><td>${l.device}</td><td><span class="badge ${l.estado==='ok'?'badge-ok':'badge-fail'}">${l.estado==='ok'?'✓ EXITOSO':'✗ FALLIDO'}</span></td></tr>`).join('');
  }
}

async function renderAdmin(){
  if(!currentUser||currentUser.rol!=='admin') return;
  const logs = await getLogs();
  await renderSolicitudes();
  document.getElementById('admin-users-list').innerHTML = USERS.map(u => {
    const isSelf = u.user === currentUser.user;
    const isAdm  = u.rol === 'admin';
    const datosExtra = u.area
      ? `<br><span style="font-size:.7rem">📍 ${u.area} | ${u.provincia} | CÓD: ${u.codigo}${u.nombreOficial ? ' | 👤 '+u.nombreOficial : ''}</span>`
      : '';
    const btnBlock = (!isSelf && !isAdm)
      ? (u.blocked
          ? `<button class="btn-unblock" onclick="toggleBlockUser('${u.user}',false)">✓ DESBLOQUEAR</button>`
          : `<button class="btn-block" onclick="toggleBlockUser('${u.user}',true)">⊘ BLOQUEAR</button>`)
      : '';
    const btnAdmin = !isSelf
      ? (isAdm
          ? `<button class="btn-block" onclick="toggleAdminRole('${u.user}')">👤 QUITAR ADMIN</button>`
          : `<button class="btn-unblock" onclick="toggleAdminRole('${u.user}')">🛡 HACER ADMIN</button>`)
      : '';
    const btnDel = (!isSelf && !isAdm)
      ? `<button class="btn-block" style="background:var(--danger,#c0392b);color:#fff" onclick="deleteUser('${u.user}')">🗑 ELIMINAR</button>`
      : '';
    return `
      <div class="user-row">
        <div class="avatar">${u.nombre.split(' ').map(x=>x[0]).slice(0,2).join('')}</div>
        <div class="user-info">
          <strong>${esc(u.nombre)}${u.blocked ? '<span class="blocked-badge">● BLOQUEADO</span>' : ''}</strong>
          <span>${esc(u.user)} · <span class="badge ${isAdm?'badge-admin':'badge-user'}">${u.rol}</span> · 📧 ${u.email || 'SIN CORREO'}${datosExtra}</span>
        </div>
        <div style="display:flex;gap:.4rem;flex-wrap:wrap;align-items:center">${btnBlock}${btnAdmin}${btnDel}</div>
      </div>`;
  }).join('');

  const byUser={};
  USERS.forEach(u=>{ byUser[u.user]={ok:0,fail:0,last:'NUNCA'}; });
  logs.forEach(l=>{ if(byUser[l.usuario]) { if(l.estado==='ok'){ byUser[l.usuario].ok++; byUser[l.usuario].last=l.fecha+' '+l.hora; } else if(l.estado==='fail') byUser[l.usuario].fail++; } });
  document.getElementById('admin-stats').innerHTML = USERS.map(u=>`<div style="padding:.5rem 0;border-bottom:1px solid #f0f2f6"><strong>${esc(u.nombre)}</strong><br><span>INGRESOS: <strong style="color:var(--success)">${byUser[u.user]?.ok||0}</strong> · FALLIDOS: <strong style="color:var(--danger)">${byUser[u.user]?.fail||0}</strong></span><br><span style="font-size:.73rem">ÚLTIMO: ${byUser[u.user]?.last}</span></div>`).join('');

  const all=[...logs];
  document.getElementById('admin-log-total').textContent = all.length;
  renderLogPage(all, 1);
  renderChart(logs);
  renderAdminFiles();
}

let _allLogs = [], _logPage = 1;
const LOG_PAGE_SIZE = 15;
function renderLogPage(logs, page){
  _allLogs = logs; _logPage = page;
  const total = logs.length;
  const pages = Math.ceil(total / LOG_PAGE_SIZE) || 1;
  const start = (page-1)*LOG_PAGE_SIZE;
  const slice = logs.slice(start, start+LOG_PAGE_SIZE);
  document.getElementById('admin-log-tbody').innerHTML = slice.map(l=>`<tr><td>${esc(l.usuario)}</td><td>${esc(l.nombre)}</td><td>${l.fecha} ${l.hora}</td><td>${l.device}</td><td><span class="badge ${l.estado==='ok'?'badge-ok':(l.estado==='aprobacion'?'badge-admin':'badge-fail')}">${l.estado==='ok'?'✓ EXITOSO':(l.estado==='aprobacion'?'✅ APROBACIÓN':'✗ FALLIDO')}</span>${l.details?`<br><small>${esc(l.details)}</small>`:''}</td></tr>`).join('');
  const pag = document.getElementById('log-pagination');
  if(pages <= 1){ pag.innerHTML=''; return; }
  let btns = '';
  if(page>1) btns += `<button class="page-btn" onclick="renderLogPage(_allLogs,${page-1})">‹</button>`;
  for(let p=Math.max(1,page-2);p<=Math.min(pages,page+2);p++)
    btns += `<button class="page-btn${p===page?' active':''}" onclick="renderLogPage(_allLogs,${p})">${p}</button>`;
  if(page<pages) btns += `<button class="page-btn" onclick="renderLogPage(_allLogs,${page+1})">›</button>`;
  btns += `<span class="page-info">PÁGINA ${page} DE ${pages} · ${total} REGISTROS</span>`;
  pag.innerHTML = btns;
}

let _accesosChart = null;
function renderChart(logs){
  const days = 14, labels = [], okC = [], failC = [];
  for(let i=days-1;i>=0;i--){
    const d = new Date(); d.setDate(d.getDate()-i);
    const label = d.toLocaleDateString('es-EC');
    const short = d.toLocaleDateString('es-EC',{day:'2-digit',month:'2-digit'});
    labels.push(short);
    const dayLogs = logs.filter(l=>l.fecha===label);
    okC.push(dayLogs.filter(l=>l.estado==='ok').length);
    failC.push(dayLogs.filter(l=>l.estado==='fail').length);
  }
  const canvas = document.getElementById('accesos-chart');
  if(!canvas) return;
  if(_accesosChart){ _accesosChart.destroy(); }
  const isDark = document.body.classList.contains('dark-mode');
  const gridColor = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.06)';
  const tickColor = isDark ? '#9ca3af' : '#5a6278';
  _accesosChart = new Chart(canvas, {
    type: 'bar',
    data: {
      labels,
      datasets: [
        { label:'EXITOSOS', data:okC, backgroundColor:'rgba(26,122,74,0.8)', borderColor:'#1a7a4a', borderWidth:1, borderRadius:3 },
        { label:'FALLIDOS', data:failC, backgroundColor:'rgba(192,57,43,0.8)', borderColor:'#c0392b', borderWidth:1, borderRadius:3 }
      ]
    },
    options: {
      responsive:true, maintainAspectRatio:true,
      plugins:{ legend:{display:false} },
      scales:{
        x:{ grid:{color:gridColor}, ticks:{color:tickColor, font:{size:10}} },
        y:{ beginAtZero:true, grid:{color:gridColor}, ticks:{color:tickColor, stepSize:1, font:{size:10}} }
      }
    }
  });
}

// ==================== ARCHIVOS UI ====================
const SECCIONES = { organico:'ORGÁNICO', orden:'ORDEN DEL CUERPO', parametros:'PARÁMETROS', reportes:'REPORTES', historia:'HISTORIA' };
const TIPO_ICONS = { pdf:'📄', word:'📝', excel:'📊', img:'🖼️', other:'📎' };
const TIPO_CSS = { pdf:'file-type-pdf', word:'file-type-word', excel:'file-type-excel', img:'file-type-img', other:'file-type-other' };

function renderSectionFiles(seccion){
  const toolbar = document.getElementById('files-toolbar-'+seccion);
  const grid = document.getElementById('files-grid-'+seccion);
  if(!toolbar) return;
  const isAdmin = currentUser && currentUser.rol==='admin';
  toolbar.innerHTML = `<div class="files-toolbar"><input class="files-search" type="text" placeholder="BUSCAR..." oninput="filterFiles('${seccion}',this.value)"/>${isAdmin ? `<button class="btn-add-file" onclick="showTab('admin');document.getElementById('af-seccion').value='${seccion}'">➕ AGREGAR</button>` : ''}</div>`;
  const files = getFiles().filter(f=>f.seccion===seccion);
  renderFilesGrid(grid, files);
}
function filterFiles(seccion, q){
  const files = getFiles().filter(f=>f.seccion===seccion && (f.nombre.toLowerCase().includes(q.toLowerCase()) || (f.desc||'').toLowerCase().includes(q.toLowerCase())));
  renderFilesGrid(document.getElementById('files-grid-'+seccion), files);
}
function renderFilesGrid(el, files){
  if(!el) return;
  if(!files.length){ el.innerHTML = `<div class="file-empty">📁 NO HAY ARCHIVOS EN ESTA SECCIÓN.</div>`; return; }
  el.innerHTML = `<div class="files-grid">${files.map(f=>{
    const viewUrl = driveViewUrl(f.urlOriginal, f.tipo);
    const dlUrl = driveDownloadUrl(f.urlOriginal);
    return `<div class="file-card"><div class="file-card-top"><div class="file-type-icon ${TIPO_CSS[f.tipo]}">${TIPO_ICONS[f.tipo]}</div><div><div class="file-card-name">${esc(f.nombre)}</div><div class="file-card-meta">${f.desc?esc(f.desc)+'<br>':''}${f.fecha}</div></div></div><div class="file-card-actions"><a class="file-card-btn file-card-btn-open" href="${viewUrl}" target="_blank">👁️ VER</a><a class="file-card-btn file-card-btn-open" href="${dlUrl}" target="_blank">⬇️ BAJAR</a>${currentUser?.rol==='admin' ? `<button class="file-card-btn file-card-btn-del" onclick="deleteFile(${f.id})">🗑</button>` : ''}</div></div>`;
  }).join('')}</div>`;
}
function renderAllSectionFiles(){ Object.keys(SECCIONES).forEach(s=>renderSectionFiles(s)); }
function renderAdminFiles(){
  const files = getFiles();
  if(!files.length){ document.getElementById('admin-files-list').innerHTML = '<div class="file-empty">SIN ARCHIVOS.</div>'; return; }
  const bySection = {};
  files.forEach(f=>{ if(!bySection[f.seccion]) bySection[f.seccion]=[]; bySection[f.seccion].push(f); });
  document.getElementById('admin-files-list').innerHTML = Object.keys(bySection).map(s=>`<div style="margin-bottom:1rem"><div class="section-badge" style="margin-bottom:.5rem">${SECCIONES[s]||s}</div><div class="files-grid">${bySection[s].map(f=>`<div class="file-card"><div class="file-card-top"><div class="file-type-icon ${TIPO_CSS[f.tipo]}">${TIPO_ICONS[f.tipo]}</div><div><div class="file-card-name">${esc(f.nombre)}</div><div class="file-card-meta">${f.fecha}</div></div></div><div class="file-card-actions"><button class="file-card-btn file-card-btn-del" onclick="deleteFile(${f.id})">🗑 ELIMINAR</button></div></div>`).join('')}</div></div>`).join('');
}
function deleteFile(id){
  const file = getFiles().find(f=>f.id===id);
  openModal('ELIMINAR ARCHIVO', `¿ELIMINAR "${file?.nombre}"?`, ()=>{
    const newFiles = getFiles().filter(f=>f.id!==id);
    saveFiles(newFiles);
    if (currentUser && currentUser.rol === 'admin') { renderAdmin(); renderAllSectionFiles(); }
  });
}
async function addFile(){
  const nombre = document.getElementById('af-nombre').value.trim().toUpperCase();
  const seccion = document.getElementById('af-seccion').value;
  const url = document.getElementById('af-url').value.trim();
  const tipo = document.getElementById('af-tipo').value;
  const desc = document.getElementById('af-desc').value.trim().toUpperCase();
  if(!nombre || !url){ showToast('COMPLETA NOMBRE Y ENLACE.', 'error'); return; }
  const newId = Date.now();
  const fecha = new Date().toLocaleDateString('es-EC');
  const entry = { id:newId, nombre, seccion, urlOriginal: url, tipo, desc, fecha, subidoPor: currentUser ? currentUser.nombre : 'ADMIN' };
  const files = getFiles();
  files.push(entry);
  saveFiles(files);
  document.getElementById('af-nombre').value = ''; document.getElementById('af-url').value = ''; document.getElementById('af-desc').value = '';
  const linea = `  { id:${newId}, nombre:'${nombre.replace(/'/g,"\\'")}', seccion:'${seccion}', tipo:'${tipo}', desc:'${desc.replace(/'/g,"\\'")}', fecha:'${fecha}', urlOriginal:'${url}' },`;
  document.getElementById('af-code-text').textContent = linea;
  document.getElementById('af-code-box').style.display = 'block';
  if (currentUser && currentUser.rol === 'admin') { renderAdmin(); renderSectionFiles(seccion); }
}
function copiarCodigo(){
  const txt = document.getElementById('af-code-text').textContent;
  navigator.clipboard.writeText(txt);
  showToast('CÓDIGO COPIADO. PÉGALO EN FILES_BASE EN EL HTML.', 'success');
}

function globalSearchFiles(){
  const query = document.getElementById('global-search-input').value.toLowerCase();
  if(!query) { document.getElementById('global-search-results').innerHTML = ''; return; }
  const files = getFiles().filter(f=>f.nombre.toLowerCase().includes(query) || (f.desc||'').toLowerCase().includes(query));
  if(!files.length) { document.getElementById('global-search-results').innerHTML = '<div class="file-empty">NO SE ENCONTRARON ARCHIVOS.</div>'; return; }
  document.getElementById('global-search-results').innerHTML = `<div class="files-grid">${files.map(f=>`<div class="file-card"><div class="file-card-top"><div class="file-type-icon ${TIPO_CSS[f.tipo]}">${TIPO_ICONS[f.tipo]}</div><div><div class="file-card-name">${esc(f.nombre)}</div><div class="file-card-meta">${SECCIONES[f.seccion]} · ${f.fecha}</div></div></div><div class="file-card-actions"><a class="file-card-btn file-card-btn-open" href="${driveViewUrl(f.urlOriginal, f.tipo)}" target="_blank">VER</a></div></div>`).join('')}</div>`;
}

// ==================== EXTRAS ====================
async function exportLogsToCSV(){
  const logs = await getLogs();
  let csv = "USUARIO,NOMBRE,EMAIL,FECHA,HORA,DISPOSITIVO,ESTADO\n";
  logs.forEach(l=>{ csv += `"${l.usuario}","${l.nombre}","${l.email||''}","${l.fecha}","${l.hora}","${l.device}","${l.estado}"\n`; });
  downloadCSV(csv, `bitacora_cte_${new Date().toISOString().slice(0,19)}.csv`);
}
function printCurrentView(){
  const tab = document.querySelector('.tab.active');
  const win = window.open('', '_blank');
  win.document.write(`<html><head><title>REPORTE CTE</title><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3&display=swap" rel="stylesheet"/><style>body{font-family:'Source Sans 3';padding:2rem;}</style></head><body>${tab.innerHTML}</body></html>`);
  win.document.close(); win.print();
}
function toggleDarkMode(){
  document.body.classList.toggle('dark-mode');
  localStorage.setItem('darkMode', document.body.classList.contains('dark-mode'));
}

async function confirmClearLogs(){
  openModal('🗑 BORRAR BITÁCORA', '¿ELIMINAR TODOS LOS REGISTROS?', async ()=>{
    const snapshot = await db.collection('logs').get();
    const batch = db.batch();
    snapshot.forEach(doc => batch.delete(doc.ref));
    await batch.commit();
    renderDashboard();
    if(currentUser && currentUser.rol === 'admin') renderAdmin();
  });
}

// ==================== MODAL Y UTILS ====================
let _modalCallback = null;
function openModal(title, msg, onConfirm){
  document.getElementById('modal-title').textContent = title;
  document.getElementById('modal-msg').textContent = msg;
  _modalCallback = onConfirm;
  document.getElementById('confirm-modal').classList.add('open');
}
function closeModal(){ document.getElementById('confirm-modal').classList.remove('open'); _modalCallback = null; }
document.getElementById('modal-ok-btn').onclick = () => { if(_modalCallback) _modalCallback(); closeModal(); };
document.getElementById('confirm-modal').addEventListener('click', e=>{ if(e.target === e.currentTarget) closeModal(); });
function mostrarError(msg){ const el = document.getElementById('login-error'); el.textContent = msg; el.style.display = 'block'; showToast(msg,'error'); setTimeout(()=>el.style.display='none', 5000); }
function mostrarExito(msg){ const el = document.getElementById('login-success'); el.textContent = msg; el.style.display = 'block'; showToast(msg,'success'); setTimeout(()=>el.style.display='none', 5000); }
function showTab(id){
  document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));
  document.getElementById('tab-'+id).classList.add('active');
  document.querySelectorAll('nav a').forEach(a=>a.classList.remove('active'));
  const lnk = [...document.querySelectorAll('nav a')].find(a=>a.getAttribute('onclick')===`showTab('${id}')`);
  if(lnk) lnk.classList.add('active');
  if(id === 'admin' && currentUser && currentUser.rol === 'admin') renderAdmin();
  if(SECCIONES[id]) renderSectionFiles(id);
}
function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

function populateUserSelector(){
  const sel = document.getElementById('user-selector');
  if(!sel) return;
  sel.innerHTML = '<option value="">— SELECCIONAR USUARIO —</option>' +
    USERS.map(u=>`<option value="${u.user}">${u.nombre} (${u.user})</option>`).join('');
}
function loadUserToEdit(){
  const username = document.getElementById('user-selector').value;
  if(!username) return;
  const u = USERS.find(x=>x.user===username);
  if(!u) return;
  document.getElementById('new-user-login').value = u.user;
  document.getElementById('new-user-name').value = u.nombre;
  document.getElementById('new-user-pass').value = '';
  document.getElementById('new-user-rol').value = u.rol;
}
async function addEditUser(){
  const login = document.getElementById('new-user-login').value.trim();
  const name = document.getElementById('new-user-name').value.trim().toUpperCase();
  const pass = document.getElementById('new-user-pass').value;
  const rol = document.getElementById('new-user-rol').value;
  if(!login||!name){ showToast('COMPLETA USUARIO Y NOMBRE.','error'); return; }
  let existing = USERS.find(u=>u.user===login);
  if(existing){
    existing.nombre = name; existing.rol = rol;
    if(pass) existing.passHash = await hashPass(pass);
    await saveUsers();
    showToast(`USUARIO ${name} ACTUALIZADO.`,'success');
  } else {
    if(!pass){ showToast('INGRESA UNA CONTRASEÑA PARA EL NUEVO USUARIO.','error'); return; }
    const newUser = { user:login, passHash: await hashPass(pass), nombre:name, rol, email:'', blocked:false, area:'', provincia:'', codigo:'', nombreOficial:'' };
    USERS.push(newUser);
    await saveUsers();
    showToast(`USUARIO ${name} CREADO.`,'success');
  }
  document.getElementById('new-user-login').value='';
  document.getElementById('new-user-name').value='';
  document.getElementById('new-user-pass').value='';
  populateUserSelector();
  if(currentUser && currentUser.rol==='admin') renderAdmin();
}
async function deleteSelectedUser(){
  const login = document.getElementById('user-selector').value;
  if(!login){ showToast('SELECCIONA UN USUARIO PRIMERO.','error'); return; }
  await deleteUser(login);
  document.getElementById('new-user-login').value='';
  document.getElementById('new-user-name').value='';
  populateUserSelector();
}

// ==================== INICIALIZACIÓN ====================
(async function init(){
  await initializeUsers();
  listenToSolicitudes();
  if(localStorage.getItem('darkMode') === 'true') document.body.classList.add('dark-mode');
  populateUserSelector();
  renderAllSectionFiles();
})();
